// Read the curated regulation archive.
//
// Source of truth: `data/regulations/regulations_index.json` — generated by
// the offline curation pipeline from the YAML anchor files under
// `data/regulations/{market}/*.yaml`. The index is rebuilt on every
// `pnpm run regen` (or equivalent) and committed.
//
// On disk this is a single small JSON file (~25 KB), so we read it on
// every request and skip a server-side cache. The Next.js route layer
// (see `app/api/regulations/archive/route.ts`) decides whether to
// unstable_cache the response for the page surface.

import fs from "node:fs/promises";
import path from "node:path";
import type { ArchiveEntry } from "./types";

const INDEX_PATH = path.join(
  process.cwd(),
  "data",
  "regulations",
  "regulations_index.json",
);

interface RawArchiveRow {
  id: string;
  region: string;
  license?: string | null;
  official_citation: string;
  short_name: string;
  source_url?: string | null;
  purchase_url?: string | null;
  article_count?: number;
}

interface RawIndex {
  schema_version?: number;
  generated_at?: string;
  count?: number;
  regulations?: RawArchiveRow[];
}

let memo: { entries: ArchiveEntry[]; generatedAt: string | null; loadedAt: number } | null = null;
const CACHE_TTL_MS = 30_000;

function normaliseRow(raw: RawArchiveRow): ArchiveEntry {
  return {
    id: raw.id,
    region: raw.region,
    officialCitation: raw.official_citation,
    shortName: raw.short_name,
    sourceUrl: raw.source_url ?? null,
    purchaseUrl: raw.purchase_url ?? null,
    articleCount: typeof raw.article_count === "number" ? raw.article_count : 0,
    license: raw.license ?? null,
  };
}

export async function readArchive(): Promise<{
  entries: ArchiveEntry[];
  generatedAt: string | null;
}> {
  if (memo && Date.now() - memo.loadedAt < CACHE_TTL_MS) {
    return { entries: memo.entries, generatedAt: memo.generatedAt };
  }
  try {
    const text = await fs.readFile(INDEX_PATH, "utf-8");
    const parsed = JSON.parse(text) as RawIndex;
    const entries = (parsed.regulations ?? []).map(normaliseRow);
    memo = { entries, generatedAt: parsed.generated_at ?? null, loadedAt: Date.now() };
    return { entries, generatedAt: parsed.generated_at ?? null };
  } catch {
    // Missing index — fresh checkout or the file was moved. Degrade to
    // empty rather than 500; the API will surface the empty state to
    // the page honestly.
    memo = { entries: [], generatedAt: null, loadedAt: Date.now() };
    return { entries: [], generatedAt: null };
  }
}

export function searchArchive(entries: ArchiveEntry[], needle: string): ArchiveEntry[] {
  if (!needle) return entries;
  const lower = needle.toLowerCase();
  return entries.filter(
    (entry) =>
      entry.id.toLowerCase().includes(lower) ||
      entry.region.toLowerCase().includes(lower) ||
      entry.shortName.toLowerCase().includes(lower) ||
      entry.officialCitation.toLowerCase().includes(lower),
  );
}
