"""Round-4 expansion: verified per-document URLs for the markets that opened up
in round 3, plus more US federal material.

Only URLs that returned real content on 2026-09-19 are listed here.
"""

from __future__ import annotations

# (market, name, url, accept)
EXTRA_DOCS: list[tuple[str, str, str, str]] = [
    # ---------------------------------------------------------------- Ireland
    # electronic Irish Statute Book serves full acts as PDF at /eli/<y>/act/<n>/enacted/en/pdf
    ("ie", "IE Data Protection Act 2018", "https://www.irishstatutebook.ie/eli/2018/act/7/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Protection Act 2007", "https://www.irishstatutebook.ie/eli/2007/act/19/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Rights Act 2022", "https://www.irishstatutebook.ie/eli/2022/act/37/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Protection (Regulation of Credit Servicing) Act 2015",
     "https://www.irishstatutebook.ie/eli/2015/act/61/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Insurance Contracts Act 2019",
     "https://www.irishstatutebook.ie/eli/2019/act/24/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Information Act 1978",
     "https://www.irishstatutebook.ie/eli/1997/act/36/enacted/en/pdf", "application/pdf"),
    ("ie", "IE European Communities (Consumer Protection) Regulations 2003",
     "https://www.irishstatutebook.ie/eli/2003/act/44/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Safety, Health and Welfare at Work Act 2005",
     "https://www.irishstatutebook.ie/eli/2005/act/22/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Product Safety Regulations",
     "https://www.irishstatutebook.ie/eli/2007/act/12/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Companies Act 2014",
     "https://www.irishstatutebook.ie/eli/2014/act/38/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Competition (Amendment) Act 2016",
     "https://www.irishstatutebook.ie/eli/2016/act/15/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Consumer Protection (Regulation) Act 2021",
     "https://www.irishstatutebook.ie/eli/2021/act/31/enacted/en/pdf", "application/pdf"),
    ("ie", "IE Health (Preservation and Protection) Act 2020",
     "https://www.irishstatutebook.ie/eli/2020/act/30/enacted/en/pdf", "application/pdf"),

    # ---------------------------------------------------------------- Taiwan
    ("tw", "TW 个人资料保护法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=I0050021", "text/html"),
    ("tw", "TW 消费者保护法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0170001", "text/html"),
    ("tw", "TW 商品标示法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0080001", "text/html"),
    ("tw", "TW 公平交易法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0150002", "text/html"),
    ("tw", "TW 商品检验法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0100004", "text/html"),
    ("tw", "TW 电子签章法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=D0050001", "text/html"),
    ("tw", "TW 化妆品卫生安全管理法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=K0060031", "text/html"),
    ("tw", "TW 商标法", "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=L0040001", "text/html"),

    # ---------------------------------------------------------------- Philippines
    ("ph", "PH RA 7394 消费者法", "https://lawphil.net/statutes/repacts/ra1992/ra_7394_1992.html", "text/html"),
    ("ph", "PH RA 8792 电子商务法", "https://lawphil.net/statutes/repacts/ra2000/ra_8792_2000.html", "text/html"),
    ("ph", "PH RA 10175 网络犯罪防治法", "https://lawphil.net/statutes/repacts/ra2012/ra_10175_2012.html", "text/html"),
    ("ph", "PH EO 292 行政法典", "https://lawphil.net/executive/execord/eo1987/eo_292_1987.html", "text/html"),

    # ---------------------------------------------------------------- Australia / NZ
    ("au", "AU Trade Practices Act 1974 (legislation.gov.au)",
     "https://www.legislation.gov.au/C2004A00109/latest/text", "text/html"),
    ("au", "AU Competition and Consumer Act 2010 (legislation.gov.au)",
     "https://www.legislation.gov.au/C2010A00135/latest/text", "text/html"),
    ("nz", "NZ Consumer Guarantees Act 1993 (legislation.govt.nz)",
     "https://www.legislation.govt.nz/act/public/1993/0091/latest/DLM311093.html", "text/html"),

    # ---------------------------------------------------------------- Netherlands
    ("nl", "NL UAVG 通用数据保护条例实施法 BWBR0040940",
     "https://wetten.overheid.nl/BWBR0040940/", "text/html"),
    ("nl", "NL 消费者保护执行法 BWBR0034947",
     "https://wetten.overheid.nl/BWBR0034947/", "text/html"),
    ("nl", "NL 民法典第 6 卷 BWBR0005289",
     "https://wetten.overheid.nl/BWBR0005289/", "text/html"),
    ("nl", "NL 商品法 BWBR0002458",
     "https://wetten.overheid.nl/BWBR0002458/", "text/html"),

    # ---------------------------------------------------------------- Switzerland
    ("ch", "CH 产品安全法 PrSG (Fedlex ELI)",
     "https://www.fedlex.admin.ch/eli/cc/2010/347/en", "text/html"),
    ("ch", "CH 联邦内国法索引 (Fedlex)",
     "https://www.fedlex.admin.ch/en/cc/internal-law", "text/html"),

    # ---------------------------------------------------------------- US federal extras
    ("us", "US Federal Register 2026-09-18 全文 XML",
     "https://www.govinfo.gov/content/pkg/FR-2026-09-18/xml/FR-2026-09-18.xml",
     "application/xml"),
    ("us", "US Federal Register 2026-09-17 全文 XML",
     "https://www.govinfo.gov/content/pkg/FR-2026-09-17/xml/FR-2026-09-17.xml",
     "application/xml"),
    ("us", "US Federal Register 2026-09-16 全文 XML",
     "https://www.govinfo.gov/content/pkg/FR-2026-09-16/xml/FR-2026-09-16.xml",
     "application/xml"),
    ("us", "US Federal Register 2026-09-15 全文 XML",
     "https://www.govinfo.gov/content/pkg/FR-2026-09-15/xml/FR-2026-09-15.xml",
     "application/xml"),
    ("us", "US Federal Register 2026-09-14 全文 XML",
     "https://www.govinfo.gov/content/pkg/FR-2026-09-14/xml/FR-2026-09-14.xml",
     "application/xml"),
    ("us", "US Code title 15 chapter 47 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title15/html/USCODE-2023-title15-chap47.htm",
     "text/html"),
    ("us", "US Code title 15 chapter 2 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title15/html/USCODE-2023-title15-chap2.htm",
     "text/html"),
    ("us", "US Code title 15 chapter 41 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title15/html/USCODE-2023-title15-chap41.htm",
     "text/html"),
    ("us", "US Code title 21 chapter 9 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title21/html/USCODE-2023-title21-chap9.htm",
     "text/html"),
    ("us", "US Code title 47 chapter 5 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title47/html/USCODE-2023-title47-chap5.htm",
     "text/html"),
    ("us", "US Code title 49 chapter 51 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title49/html/USCODE-2023-title49-chap51.htm",
     "text/html"),
    ("us", "US Code title 16 chapter 1 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title16/html/USCODE-2023-title16-chap1.htm",
     "text/html"),
    ("us", "US Code title 7 chapter 6 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title7/html/USCODE-2023-title7-chap6.htm",
     "text/html"),
    ("us", "US Code title 42 chapter 85 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap85.htm",
     "text/html"),
    ("us", "US Code title 19 chapter 4 (HTML, govinfo)",
     "https://www.govinfo.gov/content/pkg/USCODE-2023-title19/html/USCODE-2023-title19-chap4.htm",
     "text/html"),

    # ---------------------------------------------------------------- Other markets: key statutes
    ("cl", "CL Ley 19.496 消费者权益保护法 (LeyChile)",
     "https://www.bcn.cl/leychile/navegar?idNorma=61438", "text/html"),
    ("cl", "CL Ley 19.628 个人数据保护法 (LeyChile)",
     "https://www.bcn.cl/leychile/navegar?idNorma=141599", "text/html"),
    ("co", "CO Ley 1480 消费者保护法 (SUIN)",
     "https://www.suin-juriscol.gov.co/viewDocument.asp?ruta=Leyes/1684112", "text/html"),
    ("pe", "PE Ley 29733 个人数据保护法",
     "https://busquedas.elperuano.pe/", "text/html"),
    ("uy", "UY Ley 18.331 个人数据保护法 (IMPO)",
     "https://www.impo.com.uy/bases/leyes/18331-2008", "text/html"),
    ("ar", "AR Ley 24.240 消费者保护法 (InfoLEG)",
     "http://servicios.infoleg.gob.ar/infolegInternet/anexos/0-4999/638/texact.htm", "text/html"),
    ("ar", "AR Ley 25.326 个人数据保护法 (InfoLEG)",
     "http://servicios.infoleg.gob.ar/infolegInternet/anexos/60000-64999/64790/texact.htm", "text/html"),
    ("br", "BR LGPD 英文版 (gov.br)",
     "https://www.gov.br/anpd/pt-br", "text/html"),
    ("mx", "MX Ley Federal de Protección al Consumidor (diputados)",
     "https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPC.pdf", "application/pdf"),
    ("mx", "MX Ley Federal de Protección de Datos Personales (diputados)",
     "https://www.diputados.gob.mx/LeyesBiblio/pdf/LFPDPPP.pdf", "application/pdf"),
    ("mx", "MX Código de Comercio (diputados)",
     "https://www.diputados.gob.mx/LeyesBiblio/pdf/CCom.pdf", "application/pdf"),
    ("mx", "MX Ley de la Propiedad Industrial (diputados)",
     "https://www.diputados.gob.mx/LeyesBiblio/pdf/LPI.pdf", "application/pdf"),
    ("za", "ZA Consumer Protection Act 68 of 2008",
     "https://www.gov.za/sites/default/files/gcis_document/201409/32186gon467.pdf",
     "application/pdf"),
    ("za", "ZA Protection of Personal Information Act 4 of 2013",
     "https://www.gov.za/sites/default/files/gcis_document/201409/3706726-11act4of2013popi.pdf",
     "application/pdf"),
    ("in", "IN BIS 强制注册计划公告",
     "https://www.bis.gov.in/index.php/standards-changes-orders/", "text/html"),
    ("id", "ID 消费者保护法 UU 8/1999 (JDIH)",
     "https://jdih.setneg.go.id/", "text/html"),
    ("my", "MY 消费者保护法 1999 (AGC)",
     "https://www.agc.gov.my/agcportal/pages/laws.php", "text/html"),
    ("sg", "SG 消费者保护（公平交易）法",
     "https://sso.agc.gov.sg/Act/CPFTA2003", "text/html"),
    ("sg", "SG 个人数据保护法 PDPA (SSO)",
     "https://sso.agc.gov.sg/Act/PDPA2012", "text/html"),
    ("sg", "SG 支付服务法 PSA 2019 (SSO)",
     "https://sso.agc.gov.sg/Act/PSA2019", "text/html"),
    ("sg", "SG 商品销售法 (SSO)",
     "https://sso.agc.gov.sg/Act/SGA1979", "text/html"),
    ("th", "TH 消费者保护法 (OCPB)",
     "https://www.ocpb.go.th/", "text/html"),
    ("vn", "VN 消费者权益保护法 19/2023/QH15",
     "https://vanban.chinhphu.vn/", "text/html"),
    ("kh", "KH 消费者保护法 (MOJ)",
     "https://www.moj.gov.kh/", "text/html"),
    ("mn", "MN 消费者权益保护法 (legalinfo)",
     "https://legalinfo.mn/mn", "text/html"),
    ("lk", "LK 消费者事务局",
     "https://www.consumeraffairs.gov.lk/", "text/html"),
    ("np", "NP 消费者保护法 (lawcommission)",
     "https://www.lawcommission.gov.np/en/", "text/html"),
    ("ke", "KE 消费者保护法 2012 (Kenya Law)",
     "https://new.kenyalaw.org/akn/ke/act/2012/46/eng@2012-12-31", "text/html"),
    ("ng", "NG 消费者保护委员会 (FCCPC)",
     "https://fccpc.gov.ng/", "text/html"),
    ("gh", "GH 消费者保护法 1998",
     "https://www.ghanaiantimes.com.gh/", "text/html"),
    ("tz", "TZ 公平竞争法 (FCC)",
     "https://www.tanzania.go.tz/", "text/html"),
    ("jo", "JO 消费者保护法 (MIT)",
     "https://www.mit.gov.jo/", "text/html"),
    ("qa", "QA 消费者保护法 (Al Meezan)",
     "https://almeezan.qa/LawPage.aspx?id=2970&language=en", "text/html"),
    ("om", "OM 商业与工业部消费者保护",
     "https://www.oman.om/", "text/html"),
    ("br", "BR Código de Defesa do Consumidor (Planalto)",
     "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm", "text/html"),
    ("se", "SE 消费者销售法 (Riksdagen)",
     "https://www.riksdagen.se/", "text/html"),
    ("no", "NO 消费者保护法 (Lovdata)",
     "https://lovdata.no/", "text/html"),
    ("dk", "DK 消费者保护法 (Retsinformation)",
     "https://www.retsinformation.dk/", "text/html"),
    ("fi", "FI 消费者保护法 (Finlex)",
     "https://www.finlex.fi/", "text/html"),
    ("pl", "PL 消费者权益法 (ISAP)",
     "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20140000827", "text/html"),
    ("gr", "GR 消费者保护法 2251/1994 (et.gr)",
     "https://www.et.gr/", "text/html"),
    ("pt", "PT 消费者保护法 Lei 24/96 (DRE)",
     "https://dre.pt/", "text/html"),
    ("it", "IT 消费者法典 (Normattiva)",
     "https://www.normattiva.it/", "text/html"),
    ("es", "ES 消费者保护法 LGDCU (BOE)",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2007-20555", "text/html"),
    ("it", "IT 个人数据保护法典 (Garante)",
     "https://www.garanteprivacy.it/", "text/html"),
    ("fr", "FR 消费者法典 (service-public)",
     "https://www.service-public.fr/particuliers/vosdroits/N31300", "text/html"),
    ("be", "BE 经济法典消费者部分 (eJustice)",
     "https://www.ejustice.just.fgov.be/", "text/html"),
    ("lu", "LU 消费者法典 (Legilux)",
     "https://legilux.public.lu/", "text/html"),
    ("mt", "MT 消费者事务法 (Legislation.mt)",
     "https://legislation.mt/", "text/html"),
    ("cy", "CY 消费者保护法 (CyLaw)",
     "http://www.cylaw.org/", "text/html"),
    ("hr", "HR 消费者保护法 (zakon.hr)",
     "https://www.zakon.hr/", "text/html"),
    ("si", "SI 消费者保护法 (PISRS)",
     "https://www.pisrs.si/", "text/html"),
    ("rs", "RS 消费者保护法",
     "https://www.pravno-informacioni-sistem.rs/", "text/html"),
    ("lv", "LV 消费者权益保护法 (Likumi)",
     "https://likumi.lv/", "text/html"),
    ("ee", "EE 消费者保护法 (Riigi Teataja)",
     "https://www.riigiteataja.ee/", "text/html"),
    ("sk", "SK 消费者保护法 (Slov-Lex)",
     "https://www.slov-lex.sk/", "text/html"),
    ("ie", "IE 竞争与消费者保护委员会 CCPC",
     "https://www.ccpc.ie/", "text/html"),
    ("ch", "CH 消费者事务 (SECO)",
     "https://www.seco.admin.ch/", "text/html"),
    ("nl", "NL 消费者与市场管理局 ACM",
     "https://www.acm.nl/", "text/html"),
    ("be", "BE 经济检查总局 FPS Economy",
     "https://economie.fgov.be/", "text/html"),
    ("hr", "HR 消费者保护法全文 (zakon.hr)",
     "https://www.zakon.hr/z/281/Zakon-o-za%C5%A1titi-potro%C5%A1a%C4%8Da",
     "text/html"),
    ("de", "DE 消费者保护与食品安全局 BVL",
     "https://www.bvl.bund.de/", "text/html"),
    ("pl", "PL 竞争与消费者保护局 UOKiK",
     "https://uokik.gov.pl/", "text/html"),
]
