/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — returns basic status. Used by /api/health on the frontend.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — checks all critical dependencies.
         *     Used by Kubernetes / load-balancer to decide whether to route traffic here.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan-multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Multipart */
        post: operations["scan_multipart_scan_multipart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profit-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profit Report
         * @description 生成合规成本与利润分析报告。
         *
         *     接收产品类型和市场，从语料库检索相关文档，生成带完整成本表格的 markdown 报告。
         *     充电宝和乒乓球拍使用预置数据（无需 LLM 调用），其他产品尝试 LLM 填充。
         */
        post: operations["profit_report_profit_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditMetadata */
        AuditMetadata: {
            /**
             * Schemaversion
             * @default report-package/v1
             */
            schemaVersion: string;
            /** Generatedat */
            generatedAt: string;
            /**
             * Validationstatus
             * @default normalized
             * @enum {string}
             */
            validationStatus: "normalized" | "fallback" | "invalid";
            /** Validationerrors */
            validationErrors?: string[];
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Tracenodecount
             * @default 0
             */
            traceNodeCount: number;
        } & {
            [key: string]: unknown;
        };
        /** Body_scan_multipart_scan_multipart_post */
        Body_scan_multipart_scan_multipart_post: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default ["EU"]
             */
            markets: string;
            /**
             * Documents
             * @default []
             */
            documents: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Pdfs
             * @default []
             */
            pdfs: string[];
        };
        /** DecisionNode */
        DecisionNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Labelen
             * @default
             */
            labelEn: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Duration
             * @default
             */
            duration: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /**
             * Reasoningen
             * @default
             */
            reasoningEn: string;
        } & {
            [key: string]: unknown;
        };
        /** DecisionView */
        DecisionView: {
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Keyfindings */
            keyFindings?: string[];
            /**
             * Recommendedaction
             * @default
             */
            recommendedAction: string;
            /** Nodes */
            nodes?: components["schemas"]["DecisionNode"][];
        } & {
            [key: string]: unknown;
        };
        /** EvidenceBundles */
        EvidenceBundles: {
            /** Visual */
            visual?: components["schemas"]["EvidenceItem"][];
            /** Retrieval */
            retrieval?: components["schemas"]["EvidenceItem"][];
            /** Generation */
            generation?: components["schemas"]["EvidenceItem"][];
        } & {
            [key: string]: unknown;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Id */
            id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "visual" | "retrieval" | "generation" | "audit";
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProductDossier */
        ProductDossier: {
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Markets */
            markets?: string[];
            /**
             * Query
             * @default
             */
            query: string;
            /** Sourcecounts */
            sourceCounts?: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /** ProfitReport */
        ProfitReport: {
            /** Markdown */
            markdown: string;
            /**
             * Keyconclusion
             * @default
             */
            keyConclusion: string;
            /**
             * Premiumpct
             * @default
             */
            premiumPct: string;
            /**
             * Breakevenunits
             * @default
             */
            breakevenUnits: string;
            /**
             * Pricingstrategy
             * @default
             */
            pricingStrategy: string;
            /**
             * Risknote
             * @default
             */
            riskNote: string;
            /**
             * Conclusions
             * @default
             */
            conclusions: string;
            /**
             * References
             * @default
             */
            references: string;
        } & {
            [key: string]: unknown;
        };
        /** ProfitReportRequest */
        ProfitReportRequest: {
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default [
             *       "EU"
             *     ]
             */
            markets: string[];
        };
        /** ProfitReportResponse */
        ProfitReportResponse: {
            /** Status */
            status: string;
            /** Report */
            report: string;
            /** Product */
            product: string;
            /** Market */
            market: string;
        };
        /** ReportPackage */
        ReportPackage: {
            productDossier: components["schemas"]["ProductDossier"];
            /** Compliancereport */
            complianceReport: string;
            profitReport: components["schemas"]["ProfitReport"];
            roadmap: components["schemas"]["Roadmap"];
            decisionView: components["schemas"]["DecisionView"];
            evidenceBundles: components["schemas"]["EvidenceBundles"];
            auditMetadata: components["schemas"]["AuditMetadata"];
        } & {
            [key: string]: unknown;
        };
        /** Roadmap */
        Roadmap: {
            /**
             * Totaldays
             * @default 0
             */
            totalDays: number;
            /**
             * Totalcost
             * @default
             */
            totalCost: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Items */
            items?: components["schemas"]["RoadmapItem"][];
        } & {
            [key: string]: unknown;
        };
        /** RoadmapItem */
        RoadmapItem: {
            /** Id */
            id: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Titleen
             * @default
             */
            titleEn: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Descriptionen
             * @default
             */
            descriptionEn: string;
            /**
             * Type
             * @default complete
             */
            type: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Estimateddays
             * @default 0
             */
            estimatedDays: number;
            /**
             * Cost
             * @default
             */
            cost: string;
            /** Documents */
            documents?: string[];
            /** Documentsen */
            documentsEn?: string[];
        } & {
            [key: string]: unknown;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default [
             *       "EU"
             *     ]
             */
            markets: string[];
            /** Vision Result */
            vision_result?: {
                [key: string]: unknown;
            } | null;
            /** Images */
            images?: {
                [key: string]: unknown;
            }[] | null;
            /** Documents */
            documents?: {
                [key: string]: unknown;
            }[] | null;
            /** Pdfs */
            pdfs?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Status */
            status: string;
            /** Report */
            report: string;
            /** Agent Trace */
            agent_trace: {
                [key: string]: unknown;
            }[];
            /** Loop Count */
            loop_count: number;
            /** Documents */
            documents?: {
                [key: string]: unknown;
            }[] | null;
            report_package?: components["schemas"]["ReportPackage"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_multipart_scan_multipart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_multipart_scan_multipart_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profit_report_profit_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfitReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfitReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
