/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Scan
         * @description Create a scan session.
         *
         *     ``declared_facts`` (J09): a JSON object of user-stated product facts
         *     (e.g. ``{"battery": "absent"}``) collected by the upload wizard's
         *     conditional questions. Malformed JSON is ignored — the facts are an
         *     enhancement to applicability, never a request requirement.
         *     ``userDeclaredFacts`` is the browser's legacy field name for the same
         *     payload (the BFF used to rename it; it now forwards the multipart body
         *     verbatim, so both names are accepted).
         *
         *     ``query`` is optional here: when the browser posts its form directly the
         *     BFF no longer synthesizes the Chinese query string, so an empty ``query``
         *     falls back to the same wording the BFF used to build.
         */
        post: operations["create_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_v1_scans__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Scan */
        delete: operations["delete_scan_api_v1_scans__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap */
        get: operations["get_roadmap_api_v1_scans__session_id__roadmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_v1_scans__session_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Evidence
         * @description Attach supplementary photos/documents to a completed scan.
         *
         *     The evidence request merge (多个待补项合并为一个请求) happens on the
         *     frontend VM; this endpoint only persists files + idempotency marker.
         */
        post: operations["append_evidence_api_v1_scans__session_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Revision
         * @description Idempotently queue a revision re-run over the session's evidence.
         *
         *     MUST be `async def`: the service's `request_revision` spawns the re-run
         *     task via `asyncio.create_task`, which requires a RUNNING event loop. A
         *     sync `def` handler runs in Starlette's threadpool, where there is no
         *     running loop — the spawn raised RuntimeError and the route returned
         *     503 SCAN_QUEUE_UNAVAILABLE for every revision request (red-team probe
         *     2026-09-14: "coroutine 'ScanService._run_job' was never awaited").
         */
        post: operations["request_revision_api_v1_scans__session_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{session_id}/assets/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_scans__session_id__assets__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — minimal public surface (status only).
         *
         *     Frontend ``/api/health`` consumes only ``status`` (see
         *     ``app/api/health/route.ts``). Detailed fields (demo_mode,
         *     embedding_provider, dense_dim_mismatch_count, version) are gated behind
         *     ``_is_privileged`` so an unauthenticated internet caller cannot probe
         *     the deployment mode or embedding provider.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — checks all critical dependencies.
         *     Used by Kubernetes / load-balancer to decide whether to route traffic here.
         *
         *     P1-5: ``ready``, ``checks``, and ``version`` are ALWAYS returned so k8s
         *     probes work without credentials (the test suite also asserts these).
         *     Sensitive diagnostics (demo_mode, pipeline) are gated behind
         *     ``_is_privileged``.
         *
         *     De-RAG §7.7: readiness gates on the KB + regulation library (the
         *     generator's actual inputs) instead of the deleted retrieval stack.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/watchdog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Watchdog
         * @description Operational view of the regulation watchdog (2026-09-17).
         *
         *     Read-only: returns the latest pass result + per-source state
         *     without restarting anything or invalidating any cache. The endpoint
         *     sits under /health/* so it stays un-gated by RAG_INTERNAL_SECRET
         *     (operators need it during incidents when auth is the suspect) — the
         *     payload exposes no secrets, only file-derived state.
         */
        get: operations["health_watchdog_health_watchdog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan-multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Multipart */
        post: operations["scan_multipart_scan_multipart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profit-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profit Report
         * @description 生成合规成本与利润分析报告。
         *
         *     接收产品类型和市场，从语料库检索相关文档，生成带完整成本表格的 markdown 报告。
         *     充电宝和乒乓球拍使用预置数据（无需 LLM 调用），其他产品尝试 LLM 填充。
         */
        post: operations["profit_report_profit_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regulation
         * @description Return one regulation from `data/regulations/{region}/*.yaml`.
         *
         *     Public responses surface `articles[]` (with `text`) so the viewer
         *     can render the article body + apply the `hl` highlight from the
         *     URL. Private responses (GB/ASTM/UL) only return metadata + key
         *     points + purchase_url; `articles` is empty so the client knows to
         *     render the "metadata only" view (spec §7.5 step 6).
         */
        get: operations["get_regulation_api_v1_regulations__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiEnvelope[CreatedScanData] */
        ApiEnvelope_CreatedScanData_: {
            data: components["schemas"]["CreatedScanData"] | null;
            error: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[NoneType] */
        ApiEnvelope_NoneType_: {
            /** Data */
            data: null;
            error: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[dict[str, Any]] */
        ApiEnvelope_dict_str__Any__: {
            /** Data */
            data: {
                [key: string]: unknown;
            } | null;
            error: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[dict[str, Any]]] */
        ApiEnvelope_list_dict_str__Any___: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[] | null;
            error: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApiMeta */
        ApiMeta: {
            /** Requestid */
            requestId: string;
        };
        /** AuditMetadata */
        AuditMetadata: {
            /**
             * Schemaversion
             * @default report-package/v1
             */
            schemaVersion: string;
            /** Generatedat */
            generatedAt: string;
            /**
             * Validationstatus
             * @default normalized
             * @enum {string}
             */
            validationStatus: "normalized" | "fallback" | "invalid";
            /** Validationerrors */
            validationErrors?: string[];
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Tracenodecount
             * @default 0
             */
            traceNodeCount: number;
            finance?: components["schemas"]["FinanceValidation"];
            decisionView?: components["schemas"]["SubReportValidation"];
            roadmap?: components["schemas"]["SubReportValidation"];
            evidenceBundles?: components["schemas"]["SubReportValidation"];
        } & {
            [key: string]: unknown;
        };
        /** Body_append_evidence_api_v1_scans__session_id__evidence_post */
        Body_append_evidence_api_v1_scans__session_id__evidence_post: {
            /**
             * Idempotency Key
             * @default
             */
            idempotency_key: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Documents
             * @default []
             */
            documents: string[];
        };
        /** Body_create_scan_api_v1_scans_post */
        Body_create_scan_api_v1_scans_post: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default electronics
             */
            category: string;
            /**
             * Markets
             * @default ["EU"]
             */
            markets: string;
            /**
             * Declared Facts
             * @default
             */
            declared_facts: string;
            /**
             * User Declared Facts
             * @default
             */
            user_declared_facts: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Documents
             * @default []
             */
            documents: string[];
        };
        /** Body_scan_multipart_scan_multipart_post */
        Body_scan_multipart_scan_multipart_post: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default ["EU"]
             */
            markets: string;
            /**
             * Documents
             * @default []
             */
            documents: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Pdfs
             * @default []
             */
            pdfs: string[];
        };
        /**
         * CitationRef
         * @description Per-claim citation to a specific article in a regulation.
         *
         *     Spec: docs/plans/2026-09-11-de-rag-evidence-spec.md §3.3 + §4.
         *
         *     `quote_span` is populated by `quote_matcher.match_quote` AFTER the LLM
         *     returns its output — the LLM only fills `quote`. Front-end uses
         *     `quote_span` to render `<mark>` highlighting on the document viewer
         *     page (§4.4).
         *
         *     `match_status` is a three-state enumeration (spec §4.3):
         *       - matched                — `quote` is found verbatim (or whitespace-normalized)
         *                                 in the article text; `quote_span` is set.
         *       - fallback_article_only  — article exists but quote doesn't match; chip
         *                                 navigates to the article but no highlight.
         *       - unmatched              — article id is unknown; chip is flagged ✗.
         */
        CitationRef: {
            /** Doc Id */
            doc_id: string;
            /** Article Id */
            article_id: string;
            /**
             * Official Citation
             * @default
             */
            official_citation: string;
            /**
             * Quote
             * @default
             */
            quote: string;
            /** Quote Span */
            quote_span?: [
                number,
                number
            ] | null;
            /** Match Status */
            match_status?: ("matched" | "fallback_article_only" | "unmatched") | null;
        } & {
            [key: string]: unknown;
        };
        /** CreatedScanData */
        CreatedScanData: {
            /** Sessionid */
            sessionId: string;
            /** Accesstoken */
            accessToken: string;
            /** Status */
            status: string;
            /** Pollurl */
            pollUrl: string;
        };
        /** DecisionNode */
        DecisionNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Labelen
             * @default
             */
            labelEn: string;
            /**
             * Severity
             * @default info
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "info";
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Duration
             * @default
             */
            duration: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /**
             * Reasoningen
             * @default
             */
            reasoningEn: string;
        } & {
            [key: string]: unknown;
        };
        /** DecisionView */
        DecisionView: {
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Keyfindings */
            keyFindings?: string[];
            /**
             * Recommendedaction
             * @default
             */
            recommendedAction: string;
            /** Nodes */
            nodes?: components["schemas"]["DecisionNode"][];
            /**
             * Verdict
             * @default
             */
            verdict: string;
            /**
             * Risklevel
             * @default
             */
            riskLevel: string;
        } & {
            [key: string]: unknown;
        };
        /** EvidenceBundles */
        EvidenceBundles: {
            /** Visual */
            visual?: components["schemas"]["EvidenceItem"][];
            /** Retrieval */
            retrieval?: components["schemas"]["EvidenceItem"][];
            /** Generation */
            generation?: components["schemas"]["EvidenceItem"][];
        } & {
            [key: string]: unknown;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Id */
            id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "visual" | "retrieval" | "generation" | "audit";
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * FinanceValidation
         * @description Per-sub-report validation, surfaced separately from the package-level
         *     `validationStatus` so a malformed sub-report (e.g. bad currency arithmetic
         *     in profit/finance) does NOT downgrade the whole compliance package. The
         *     profit page reads `finance.validationStatus` to render its own notice.
         *
         *     Audit P0-D: extended the same pattern to decisionView/roadmap/
         *     evidenceBundles — previously only finance had isolation, so a missing
         *     decisionView node could still flip the package to "invalid" and trigger
         *     the red `DegradedBanner`.
         */
        FinanceValidation: {
            /**
             * Validationstatus
             * @default valid
             * @enum {string}
             */
            validationStatus: "valid" | "invalid";
            /** Errors */
            errors?: string[];
        } & {
            [key: string]: unknown;
        };
        /** FinancialCostComparison */
        FinancialCostComparison: {
            barebone: components["schemas"]["FinancialCostSummary"];
            compliant: components["schemas"]["FinancialCostSummary"];
        };
        /**
         * FinancialCostSummary
         * @description Per-unit finance values that may drive the detailed profit board.
         *
         *     Audit 2026-09-13 §10.2: ``gp`` may be NEGATIVE — a real product can
         *     sell at a loss, and the old non-negative constraint made the model
         *     (or a normalizer) silently clamp losses to 0 to pass validation.
         *     Cost fields stay non-negative; only the profit fields accept losses.
         */
        FinancialCostSummary: {
            /** Bom */
            bom: number;
            /** Packaging */
            packaging: number;
            /** Cert */
            cert: number;
            /** Epr */
            epr: number;
            /** Logistics */
            logistics: number;
            /** Warranty */
            warranty: number;
            /** Asp */
            asp: number;
            /** Total */
            total: number;
            /** Gp */
            gp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProductDossier */
        ProductDossier: {
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Markets */
            markets?: string[];
            /**
             * Query
             * @default
             */
            query: string;
            /** Sourcecounts */
            sourceCounts?: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /** ProfitReport */
        ProfitReport: {
            /** Markdown */
            markdown: string;
            /**
             * Keyconclusion
             * @default
             */
            keyConclusion: string;
            /**
             * Premiumpct
             * @default
             */
            premiumPct: string;
            /**
             * Breakevenunits
             * @default
             */
            breakevenUnits: string;
            /**
             * Pricingstrategy
             * @default
             */
            pricingStrategy: string;
            /**
             * Risknote
             * @default
             */
            riskNote: string;
            /**
             * Conclusions
             * @default
             */
            conclusions: string;
            /**
             * References
             * @default
             */
            references: string;
            structuredFields?: components["schemas"]["StructuredProfitFields"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ProfitReportRequest */
        ProfitReportRequest: {
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default [
             *       "EU"
             *     ]
             */
            markets: string[];
        };
        /** ProfitReportResponse */
        ProfitReportResponse: {
            /** Status */
            status: string;
            /** Report */
            report: string;
            /** Product */
            product: string;
            /** Market */
            market: string;
        };
        /** ReportPackage */
        ReportPackage: {
            productDossier: components["schemas"]["ProductDossier"];
            /** Compliancereport */
            complianceReport: string;
            profitReport: components["schemas"]["ProfitReport"];
            roadmap: components["schemas"]["Roadmap"];
            decisionView: components["schemas"]["DecisionView"];
            evidenceBundles: components["schemas"]["EvidenceBundles"];
            auditMetadata: components["schemas"]["AuditMetadata"];
            /** Citations */
            citations?: components["schemas"]["CitationRef"][];
            /** Evidencepack */
            evidencePack?: components["schemas"]["CitationRef"][];
            /** Observations */
            observations?: {
                [key: string]: unknown;
            }[];
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
            /** Selectedcheckids */
            selectedCheckIds?: string[];
        } & {
            [key: string]: unknown;
        };
        /** Roadmap */
        Roadmap: {
            /**
             * Totaldays
             * @default 0
             */
            totalDays: number;
            /**
             * Totalcost
             * @default
             */
            totalCost: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Items */
            items?: components["schemas"]["RoadmapItem"][];
        } & {
            [key: string]: unknown;
        };
        /** RoadmapItem */
        RoadmapItem: {
            /** Id */
            id: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Titleen
             * @default
             */
            titleEn: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Descriptionen
             * @default
             */
            descriptionEn: string;
            /**
             * Type
             * @default complete
             */
            type: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Estimateddays
             * @default 0
             */
            estimatedDays: number;
            /**
             * Cost
             * @default
             */
            cost: string;
            /** Documents */
            documents?: string[];
            /** Documentsen */
            documentsEn?: string[];
        } & {
            [key: string]: unknown;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Product
             * @default
             */
            product: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Markets
             * @default [
             *       "EU"
             *     ]
             */
            markets: string[];
            /** Vision Result */
            vision_result?: {
                [key: string]: unknown;
            } | null;
            /** Images */
            images?: {
                [key: string]: unknown;
            }[] | null;
            /** Documents */
            documents?: {
                [key: string]: unknown;
            }[] | null;
            /** Pdfs */
            pdfs?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Status */
            status: string;
            /** Report */
            report: string;
            /** Agent Trace */
            agent_trace: {
                [key: string]: unknown;
            }[];
            /** Loop Count */
            loop_count: number;
            /** Documents */
            documents?: {
                [key: string]: unknown;
            }[] | null;
            report_package?: components["schemas"]["ReportPackage"] | null;
        };
        /**
         * StructuredProfitFields
         * @description Optional extension fields; structured finance is strict when supplied.
         *
         *     Plan 2026-09-13 §10.2 — provenance: numbers are only trustworthy when
         *     the source says so. ``sourceStatus`` distinguishes a real quote
         *     ("quoted", e.g. supplier price list), a model estimate ("estimated"),
         *     and unknown ("unknown" — the historical default when the model filled
         *     numbers without any source). ``asOf`` + ``sourceRefs`` make the claim
         *     checkable; the frontend renders estimated/unknown as 估算/待询价.
         */
        StructuredProfitFields: {
            /** Currency */
            currency: string;
            costComparison: components["schemas"]["FinancialCostComparison"];
            /**
             * Sourcestatus
             * @default unknown
             * @enum {string}
             */
            sourceStatus: "quoted" | "estimated" | "unknown";
            /**
             * Asof
             * @default
             */
            asOf: string;
            /** Sourcerefs */
            sourceRefs?: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * SubReportValidation
         * @description Per-scene validation tracker for `decisionView`, `roadmap`, and
         *     `evidenceBundles`. Mirrors `FinanceValidation` so a malformed sub-scene
         *     surfaces as a warning without downgrading the whole package (audit P0-D).
         */
        SubReportValidation: {
            /**
             * Validationstatus
             * @default valid
             * @enum {string}
             */
            validationStatus: "valid" | "invalid";
            /** Errors */
            errors?: string[];
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_scan_api_v1_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CreatedScanData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v1_scans__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_v1_scans__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_api_v1_scans__session_id__roadmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_v1_scans__session_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_dict_str__Any___"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_evidence_api_v1_scans__session_id__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_append_evidence_api_v1_scans__session_id__evidence_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_revision_api_v1_scans__session_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_scans__session_id__assets__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 原始资产字节（图片/PDF，content-type 由后端按上传类型决定） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "*/*": string;
                };
            };
            /** @description Invalid scan access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NoneType_"];
                };
            };
            /** @description Scan asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_dict_str__Any__"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_watchdog_health_watchdog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_multipart_scan_multipart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_multipart_scan_multipart_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profit_report_profit_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfitReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfitReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regulation_api_v1_regulations__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
