import type { RegulationUpdate } from "./types";

// Static demo data. Source URLs point to official reference sites, but entries are
// curated examples and are not fetched or verified live. These are merged with
// live watchdog data by the route (see ./watchdog-source.ts); on a fresh
// install with no watchdog pass on record, the API serves ONLY these 30
// entries and reports `dataset: "static-demo"`. After the first watchdog pass
// the dataset label flips to "live+demo" and watchdog-sourced entries appear
// alongside — they never displace curated examples for markets not yet
// tracked by an official source.
export const STATIC_DEMO: RegulationUpdate[] = [
  {
    id: "reg-001",
    market: "EU",
    title: "REACH 高关注物质候选清单扩展",
    titleEn: "REACH SVHC Candidate List Expansion",
    publishDate: "2026-05-10",
    effectiveDate: "2026-07-01",
    affectedCategories: ["电子电器", "玩具", "家具", "纺织品"],
    affectedCategoriesEn: ["Electronics", "Toys", "Furniture", "Textiles"],
    summary:
      "ECHA 候选清单新增多种高关注物质，重点影响含塑化剂、阻燃剂或表面涂层的消费品。出口商需要更新物料声明和供应商符合性证明。",
    summaryEn:
      "ECHA adds several substances of very high concern, affecting products with plasticizers, flame retardants, or coated surfaces. Exporters should refresh material declarations and supplier compliance evidence.",
    sourceAgency: "欧洲化学品管理局 ECHA",
    sourceAgencyEn: "European Chemicals Agency (ECHA)",
    sourceUrl: "https://echa.europa.eu/candidate-list-en",
    riskLevel: "high",
    changeType: "revision",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "含复杂塑料件、胶黏剂或涂层的 SKU 需要重新做 BOM 物质筛查，部分供应商可能需要补充测试报告。",
    businessImpactEn:
      "SKUs with complex plastic parts, adhesives, or coatings need renewed BOM substance screening; some suppliers may need updated test reports.",
    requirements: ["更新 SVHC 声明", "核查 SCIP 通报适用性", "保存供应商物质证明"],
    requirementsEn: ["Refresh SVHC declarations", "Check SCIP notification applicability", "Keep supplier substance evidence"],
    recommendedActions: ["优先筛查高销量电子配件", "向一级供应商补采 MSDS/材质声明", "对高风险材质抽样送检"],
    recommendedActionsEn: [
      "Prioritize high-volume electronic accessories",
      "Collect MSDS/material declarations from tier-1 suppliers",
      "Sample-test high-risk materials",
    ],
    lastVerifiedAt: "2026-05-21",
  },
  {
    id: "reg-002",
    market: "US",
    title: "CPSIA 儿童产品铅含量与证书要求更新",
    titleEn: "CPSIA Lead Content and Children Product Certificate Update",
    publishDate: "2026-05-08",
    effectiveDate: "2026-06-01",
    affectedCategories: ["玩具", "儿童用品", "家具", "饰品"],
    affectedCategoriesEn: ["Toys", "Children's Products", "Furniture", "Accessories"],
    summary:
      "CPSC 强化儿童产品中铅含量、可接触涂层和儿童产品证书 CPC 的抽查要求，跨境卖家需要确保实验室报告与批次信息一致。",
    summaryEn:
      "CPSC tightens scrutiny of lead content, accessible coatings, and Children Product Certificates. Cross-border sellers should align lab reports with batch records.",
    sourceAgency: "美国消费品安全委员会 CPSC",
    sourceAgencyEn: "U.S. Consumer Product Safety Commission (CPSC)",
    sourceUrl: "https://www.cpsc.gov/Regulations-Laws--Standards/Rulemaking/Final",
    riskLevel: "critical",
    changeType: "enforcement",
    status: "执法窗口临近",
    statusEn: "Enforcement window approaching",
    businessImpact: "儿童类目若证书缺失或报告与型号不匹配，可能触发平台下架、海关扣留或召回。",
    businessImpactEn:
      "Children's product listings with missing certificates or mismatched test reports may face marketplace takedowns, customs holds, or recalls.",
    requirements: ["CPC 证书覆盖每个型号", "第三方实验室报告可追溯", "标签包含进口商与批次信息"],
    requirementsEn: [
      "CPC covers every model",
      "Third-party lab reports are traceable",
      "Labels include importer and batch details",
    ],
    recommendedActions: ["按 ASIN/SKU 建证书索引", "抽查儿童可接触部件", "补齐美国进口商信息"],
    recommendedActionsEn: [
      "Build a certificate index by ASIN/SKU",
      "Spot-check accessible children's product parts",
      "Complete U.S. importer details",
    ],
    lastVerifiedAt: "2026-05-20",
  },
  {
    id: "reg-003",
    market: "CN",
    title: "两用物项出口管制许可规则细化",
    titleEn: "Dual-Use Export Control Licensing Rules Clarified",
    publishDate: "2026-05-05",
    effectiveDate: "2026-06-15",
    affectedCategories: ["电子元器件", "机械设备", "化学品", "传感器"],
    affectedCategoriesEn: ["Electronic Components", "Machinery", "Chemicals", "Sensors"],
    summary:
      "主管部门细化两用物项分类、最终用户声明和许可证申请材料。涉及高性能芯片、测量设备和特定化学品的出口订单需要提前评估。",
    summaryEn:
      "Authorities clarify dual-use classification, end-user statements, and license dossier requirements. Orders involving advanced chips, measurement equipment, and specific chemicals need early assessment.",
    sourceAgency: "商务部",
    sourceAgencyEn: "Ministry of Commerce",
    sourceUrl: "https://www.mofcom.gov.cn/",
    riskLevel: "critical",
    changeType: "new",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "高风险订单审批周期可能拉长，缺少最终用途证明会影响发货与收款节奏。",
    businessImpactEn:
      "Approval timelines for high-risk orders may lengthen; missing end-use evidence can affect shipment and payment schedules.",
    requirements: ["建立物项分类记录", "收集最终用户和最终用途声明", "保留交易筛查日志"],
    requirementsEn: [
      "Maintain item classification records",
      "Collect end-user and end-use statements",
      "Keep transaction screening logs",
    ],
    recommendedActions: ["把出口管制筛查前置到报价阶段", "为敏感客户设置人工复核", "准备许可证申请模板"],
    recommendedActionsEn: [
      "Move export-control screening to quotation stage",
      "Add manual review for sensitive customers",
      "Prepare license application templates",
    ],
    lastVerifiedAt: "2026-05-22",
  },
  {
    id: "reg-004",
    market: "EU",
    title: "RoHS 豁免条款续期和限制物质复核",
    titleEn: "RoHS Exemption Renewal and Restricted Substance Review",
    publishDate: "2026-04-28",
    effectiveDate: "2026-10-01",
    affectedCategories: ["电子电器", "照明", "医疗设备", "家电"],
    affectedCategoriesEn: ["Electronics", "Lighting", "Medical Devices", "Home Appliances"],
    summary:
      "欧盟继续复核 RoHS 豁免条款和部分限制物质阈值。依赖铅焊料、特定阻燃剂或豁免材料的产品需要确认豁免有效期。",
    summaryEn:
      "The EU continues reviewing RoHS exemptions and restricted substance thresholds. Products relying on lead solder, specific flame retardants, or exempted materials should confirm exemption validity.",
    sourceAgency: "欧盟委员会",
    sourceAgencyEn: "European Commission",
    sourceUrl: "https://environment.ec.europa.eu/topics/waste-and-recycling/rohs-directive_en",
    riskLevel: "high",
    changeType: "revision",
    status: "草案跟踪",
    statusEn: "Draft monitored",
    businessImpact: "老款电子产品可能需要重新评估物料替代方案，并预留重新测试和 DoC 更新周期。",
    businessImpactEn:
      "Legacy electronics may need material substitution review plus lead time for retesting and Declaration of Conformity updates.",
    requirements: ["复核 RoHS 豁免编号", "更新技术文档和 DoC", "确认供应商无铅声明"],
    requirementsEn: ["Review RoHS exemption IDs", "Update technical files and DoC", "Confirm supplier lead-free statements"],
    recommendedActions: ["列出依赖豁免的 SKU", "向 ODM 确认替代料计划", "把 RoHS 报告有效期纳入预警"],
    recommendedActionsEn: [
      "List SKUs relying on exemptions",
      "Confirm substitution plans with ODMs",
      "Add RoHS report expiry to alerts",
    ],
    lastVerifiedAt: "2026-05-18",
  },
  {
    id: "reg-005",
    market: "UK",
    title: "UKCA 标志过渡安排和 CE 认可边界更新",
    titleEn: "UKCA Transition and CE Recognition Boundary Update",
    publishDate: "2026-04-25",
    effectiveDate: "2026-12-31",
    affectedCategories: ["电子电器", "机械", "无线设备", "医疗设备"],
    affectedCategoriesEn: ["Electronics", "Machinery", "Radio Equipment", "Medical Devices"],
    summary:
      "英国继续调整 UKCA 和 CE 标志认可安排，不同产品法规下的过渡期不完全一致。卖家需要按法规族确认标签和合格评定路径。",
    summaryEn:
      "The UK continues adjusting UKCA and CE recognition arrangements, with transition periods varying by product regulation. Sellers should verify labeling and conformity routes by regulation family.",
    sourceAgency: "英国商业与贸易部",
    sourceAgencyEn: "UK Department for Business and Trade",
    sourceUrl: "https://www.gov.uk/guidance/using-the-ukca-marking",
    riskLevel: "medium",
    changeType: "revision",
    status: "过渡期",
    statusEn: "Transition period",
    businessImpact: "包装、说明书和 DoC 可能需要双标识策略，英国本地责任主体信息也要同步维护。",
    businessImpactEn:
      "Packaging, manuals, and DoCs may need a dual-marking strategy, alongside maintained UK responsible person information.",
    requirements: ["确认适用法规族", "维护 UK DoC 或 CE DoC", "核查英国责任主体信息"],
    requirementsEn: ["Confirm applicable regulation family", "Maintain UK or CE DoC", "Verify UK responsible person details"],
    recommendedActions: ["把英国市场 SKU 单独建标签规则", "检查包装库存消耗计划", "同步客服和售后合规话术"],
    recommendedActionsEn: [
      "Create UK-specific labeling rules by SKU",
      "Check packaging inventory run-down plans",
      "Align customer support compliance messaging",
    ],
    lastVerifiedAt: "2026-05-19",
  },
  {
    id: "reg-006",
    market: "AE",
    title: "阿联酋低电压设备 ECAS 与能效标签要求更新",
    titleEn: "UAE ECAS and Energy Label Requirements for Low Voltage Equipment",
    publishDate: "2026-04-20",
    effectiveDate: "2026-08-01",
    affectedCategories: ["小家电", "电源适配器", "IT 设备", "照明"],
    affectedCategoriesEn: ["Small Appliances", "Power Adapters", "IT Equipment", "Lighting"],
    summary:
      "阿联酋更新低电压设备符合性方案，部分产品需要同步满足 ECAS 证书、能效标签和进口清关文件要求。",
    summaryEn:
      "The UAE updates conformity expectations for low-voltage equipment; some products must align ECAS certificates, energy labels, and import clearance documents.",
    sourceAgency: "阿联酋工业与先进技术部 MoIAT",
    sourceAgencyEn: "UAE Ministry of Industry and Advanced Technology (MoIAT)",
    sourceUrl: "https://moiat.gov.ae/",
    riskLevel: "high",
    changeType: "enforcement",
    status: "执法窗口临近",
    statusEn: "Enforcement window approaching",
    businessImpact: "证书、标签或清关文件不一致会直接影响海湾仓发货和本地进口商清关效率。",
    businessImpactEn:
      "Inconsistent certificates, labels, or clearance documents can directly affect Gulf warehouse dispatch and importer clearance speed.",
    requirements: ["ECAS 证书覆盖型号", "能效标签与包装一致", "进口商资料与证书一致"],
    requirementsEn: ["ECAS certificate covers model numbers", "Energy label matches packaging", "Importer details match certificates"],
    recommendedActions: ["核对证书型号命名", "提前排查标签版式", "与中东进口商确认清关模板"],
    recommendedActionsEn: [
      "Check model naming on certificates",
      "Review label artwork early",
      "Confirm clearance templates with Middle East importers",
    ],
    lastVerifiedAt: "2026-05-17",
  },
  {
    id: "reg-007",
    market: "SA",
    title: "SABER 平台产品证书和装运证书流程收紧",
    titleEn: "SABER Product and Shipment Certificate Workflow Tightened",
    publishDate: "2026-04-15",
    effectiveDate: "2026-07-01",
    affectedCategories: ["电子电器", "纺织品", "化妆品", "家居用品"],
    affectedCategoriesEn: ["Electronics", "Textiles", "Cosmetics", "Home Goods"],
    summary:
      "沙特继续强化 SABER 平台中产品证书 PCoC 和装运证书 SCoC 的一致性校验，进口商、HS Code 和产品图片需要保持一致。",
    summaryEn:
      "Saudi Arabia tightens consistency checks between SABER Product Certificates and Shipment Certificates, including importer, HS code, and product image alignment.",
    sourceAgency: "沙特标准、计量与质量组织 SASO",
    sourceAgencyEn: "Saudi Standards, Metrology and Quality Organization (SASO)",
    sourceUrl: "https://www.saso.gov.sa/",
    riskLevel: "high",
    changeType: "enforcement",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "资料不一致会导致证书驳回或清关延迟，特别影响季节性促销和大促补货。",
    businessImpactEn:
      "Inconsistent documentation can cause certificate rejection or customs delays, especially affecting seasonal launches and promotion replenishment.",
    requirements: ["PCoC 与 SCoC 信息一致", "HS Code 与类目证书匹配", "产品图片和包装图清晰"],
    requirementsEn: ["PCoC and SCoC details match", "HS code aligns with category certificate", "Product and packaging images are clear"],
    recommendedActions: ["建立 SABER 字段校验表", "把中东 SKU 与 HS Code 绑定", "提前预约认证机构审核"],
    recommendedActionsEn: [
      "Create a SABER field checklist",
      "Bind Middle East SKUs to HS codes",
      "Book conformity body review early",
    ],
    lastVerifiedAt: "2026-05-16",
  },
  {
    id: "reg-008",
    market: "AU",
    title: "澳大利亚线上产品安全监管现代化",
    titleEn: "Australia Online Product Safety Modernization",
    publishDate: "2026-04-10",
    effectiveDate: "2026-09-01",
    affectedCategories: ["玩具", "消费电子", "家具", "婴童用品"],
    affectedCategoriesEn: ["Toys", "Consumer Electronics", "Furniture", "Baby Products"],
    summary:
      "澳大利亚加强线上渠道产品安全监管，平台和卖家需要更快响应事故报告、禁售令和强制召回通知。",
    summaryEn:
      "Australia strengthens online product safety oversight, requiring platforms and sellers to respond faster to incident reports, bans, and mandatory recall notices.",
    sourceAgency: "澳大利亚竞争与消费者委员会 ACCC",
    sourceAgencyEn: "Australian Competition and Consumer Commission (ACCC)",
    sourceUrl: "https://www.productsafety.gov.au/",
    riskLevel: "medium",
    changeType: "revision",
    status: "咨询后跟踪",
    statusEn: "Post-consultation monitoring",
    businessImpact: "产品安全事件的响应 SLA 会影响平台账号健康度，也会增加售后和召回流程成本。",
    businessImpactEn:
      "Product safety incident response SLAs can affect marketplace account health and increase after-sales and recall process costs.",
    requirements: ["建立事故上报流程", "保留销售批次记录", "准备召回通知模板"],
    requirementsEn: ["Set up incident reporting workflow", "Keep sales batch records", "Prepare recall notice templates"],
    recommendedActions: ["对澳洲热销品做风险排序", "配置客服事故关键词", "建立停售和召回审批链"],
    recommendedActionsEn: [
      "Risk-rank Australia best sellers",
      "Configure customer-service incident keywords",
      "Define stop-sale and recall approvals",
    ],
    lastVerifiedAt: "2026-05-15",
  },
  {
    id: "reg-009",
    market: "JP",
    title: "日本 PSE 对锂电池和无线设备范围复核",
    titleEn: "Japan PSE Scope Review for Lithium Batteries and Wireless Devices",
    publishDate: "2026-04-05",
    effectiveDate: "2026-08-15",
    affectedCategories: ["锂电池", "电源类产品", "无线设备", "家电"],
    affectedCategoriesEn: ["Lithium Batteries", "Power Products", "Wireless Devices", "Home Appliances"],
    summary:
      "日本复核电气用品安全法 PSE 适用目录，对含锂电池、电源适配器或无线模块的产品提出更清晰的分类和标识要求。",
    summaryEn:
      "Japan reviews PSE applicability for products containing lithium batteries, power adapters, or wireless modules, with clearer classification and marking expectations.",
    sourceAgency: "日本经济产业省 METI",
    sourceAgencyEn: "Japan Ministry of Economy, Trade and Industry (METI)",
    sourceUrl: "https://www.meti.go.jp/english/",
    riskLevel: "high",
    changeType: "revision",
    status: "草案跟踪",
    statusEn: "Draft monitored",
    businessImpact: "组合产品可能同时触发 PSE、TELEC 和电池运输要求，上市前资料准备周期会变长。",
    businessImpactEn:
      "Bundled products may trigger PSE, TELEC, and battery transport requirements, lengthening pre-launch dossier preparation.",
    requirements: ["确认 PSE 菱形/圆形标识", "核查无线模块认证", "保存日文说明书安全信息"],
    requirementsEn: ["Confirm diamond/circle PSE marking", "Check wireless module certification", "Keep Japanese safety manual content"],
    recommendedActions: ["拆分电池包和整机合规路径", "核对标签耐久性", "让日本代理复核说明书"],
    recommendedActionsEn: [
      "Separate battery pack and finished product compliance paths",
      "Check label durability",
      "Have Japan representative review manuals",
    ],
    lastVerifiedAt: "2026-05-14",
  },
  {
    id: "reg-010",
    market: "BR",
    title: "巴西 INMETRO 进口电子产品认证资料要求",
    titleEn: "Brazil INMETRO Documentation Requirements for Imported Electronics",
    publishDate: "2026-03-28",
    effectiveDate: "2026-07-01",
    affectedCategories: ["电子电器", "家电", "IT 设备", "电源适配器"],
    affectedCategoriesEn: ["Electronics", "Home Appliances", "IT Equipment", "Power Adapters"],
    summary:
      "巴西强化 INMETRO 认证资料、进口商授权和本地测试报告的一致性审查。进口电子产品需要提前安排本地认证机构流程。",
    summaryEn:
      "Brazil tightens INMETRO dossier, importer authorization, and local test report consistency checks. Imported electronics should plan local certification body workflows early.",
    sourceAgency: "巴西国家计量、质量和技术研究院 INMETRO",
    sourceAgencyEn: "Brazil National Institute of Metrology, Quality and Technology (INMETRO)",
    sourceUrl: "https://www.gov.br/inmetro/",
    riskLevel: "high",
    changeType: "enforcement",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "认证排期和样品测试时间可能影响巴西站点上新节奏，证书持有人变更也会带来额外成本。",
    businessImpactEn:
      "Certification scheduling and sample testing can affect Brazil launch timing; certificate-holder changes may add cost.",
    requirements: ["本地证书持有人明确", "测试报告覆盖巴西电压频率", "葡语标签和说明书齐备"],
    requirementsEn: [
      "Local certificate holder is defined",
      "Test report covers Brazil voltage/frequency",
      "Portuguese labels and manuals are complete",
    ],
    recommendedActions: ["锁定本地认证机构时间", "准备葡语包装素材", "确认进口商授权链路"],
    recommendedActionsEn: [
      "Reserve local certification body slots",
      "Prepare Portuguese packaging assets",
      "Confirm importer authorization chain",
    ],
    lastVerifiedAt: "2026-05-13",
  },
  {
    id: "reg-011",
    market: "EU",
    title: "GPSR 线上市场可追溯信息执法提醒",
    titleEn: "GPSR Online Marketplace Traceability Enforcement Reminder",
    publishDate: "2026-05-12",
    effectiveDate: "2026-06-13",
    affectedCategories: ["消费品", "家居用品", "运动户外", "电子配件"],
    affectedCategoriesEn: ["Consumer Goods", "Home Goods", "Sports & Outdoors", "Electronic Accessories"],
    summary:
      "欧盟通用产品安全法规 GPSR 对线上展示的制造商、欧盟责任人、安全警示和产品识别信息提出更严格要求。",
    summaryEn:
      "The EU General Product Safety Regulation requires stronger online display of manufacturer, EU responsible person, safety warnings, and product identification details.",
    sourceAgency: "欧盟委员会 Safety Gate",
    sourceAgencyEn: "European Commission Safety Gate",
    sourceUrl: "https://ec.europa.eu/safety-gate/",
    riskLevel: "critical",
    changeType: "enforcement",
    status: "执法窗口临近",
    statusEn: "Enforcement window approaching",
    businessImpact: "listing 页面缺少欧盟责任人或安全警示时，平台可能直接限制曝光或下架。",
    businessImpactEn:
      "Listings missing EU responsible person or safety warnings may face marketplace visibility restrictions or takedowns.",
    requirements: ["展示欧盟责任人", "提供产品识别信息", "线上展示适用安全警示"],
    requirementsEn: ["Display EU responsible person", "Provide product identification", "Show applicable safety warnings online"],
    recommendedActions: ["批量扫描 EU listing", "补齐包装和页面上的责任人信息", "建立 Safety Gate 召回监控"],
    recommendedActionsEn: [
      "Bulk-audit EU listings",
      "Add responsible person details to packaging and pages",
      "Set up Safety Gate recall monitoring",
    ],
    lastVerifiedAt: "2026-05-22",
  },
  {
    id: "reg-012",
    market: "US",
    title: "锂离子电池消费品安全抽查升级",
    titleEn: "Lithium-Ion Battery Consumer Product Safety Screening Escalation",
    publishDate: "2026-05-02",
    effectiveDate: "2026-08-15",
    affectedCategories: ["移动电源", "电动滑板车", "无线工具", "智能家居"],
    affectedCategoriesEn: ["Power Banks", "E-Scooters", "Cordless Tools", "Smart Home"],
    summary:
      "美国监管机构和平台加强对含锂电池消费品的热失控、充电保护和运输标签审查，UL/IEC 报告匹配度成为重点。",
    summaryEn:
      "U.S. regulators and marketplaces increase review of lithium battery thermal runaway, charging protection, and shipping labels; UL/IEC report matching becomes critical.",
    sourceAgency: "CPSC / 平台安全政策",
    sourceAgencyEn: "CPSC / Marketplace Safety Policies",
    sourceUrl: "https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/Fire-Safety-Information-Center",
    riskLevel: "high",
    changeType: "enforcement",
    status: "重点抽查",
    statusEn: "Priority screening",
    businessImpact: "电池报告与成品型号不匹配时，listing 审核和仓储入库可能被延迟。",
    businessImpactEn:
      "If battery reports do not match finished-goods models, listing review and fulfillment intake may be delayed.",
    requirements: ["UN38.3 和 MSDS 齐备", "充电器和电芯报告匹配", "危险品运输标签正确"],
    requirementsEn: ["UN38.3 and MSDS are available", "Charger and cell reports match", "Dangerous goods labels are correct"],
    recommendedActions: ["把电芯型号写入 SKU 主数据", "复核 FBA 危险品属性", "抽测充电保护功能"],
    recommendedActionsEn: [
      "Add cell model to SKU master data",
      "Review FBA dangerous goods attributes",
      "Sample-test charging protection",
    ],
    lastVerifiedAt: "2026-05-20",
  },
  {
    id: "reg-013",
    market: "US",
    title: "加州 Proposition 65 短版警示文本适用边界更新",
    titleEn: "California Proposition 65 Short-Form Warning Boundary Update",
    publishDate: "2026-04-18",
    effectiveDate: "2026-09-30",
    affectedCategories: ["消费品", "饰品", "电子配件", "家居用品"],
    affectedCategoriesEn: ["Consumer Goods", "Accessories", "Electronic Accessories", "Home Goods"],
    summary:
      "加州继续调整短版警示文本适用场景，产品页面、包装和说明书上的化学物质警示需要保持一致。",
    summaryEn:
      "California continues refining short-form warning use cases; chemical warnings on product pages, packaging, and manuals should remain consistent.",
    sourceAgency: "加州环境健康危害评估办公室 OEHHA",
    sourceAgencyEn: "California Office of Environmental Health Hazard Assessment (OEHHA)",
    sourceUrl: "https://oehha.ca.gov/proposition-65",
    riskLevel: "medium",
    changeType: "revision",
    status: "过渡期",
    statusEn: "Transition period",
    businessImpact: "警示语不一致容易触发平台审核、消费者投诉和加州私人执法风险。",
    businessImpactEn:
      "Inconsistent warnings can trigger marketplace review, consumer complaints, and private enforcement risk in California.",
    requirements: ["识别需警示化学物质", "线上线下警示一致", "保留供应商化学声明"],
    requirementsEn: ["Identify chemicals requiring warnings", "Keep online/offline warnings consistent", "Retain supplier chemical declarations"],
    recommendedActions: ["建立 Prop 65 文案库", "按类目配置页面警示", "复核美国包装库存"],
    recommendedActionsEn: [
      "Build a Prop 65 warning copy library",
      "Configure page warnings by category",
      "Review U.S. packaging inventory",
    ],
    lastVerifiedAt: "2026-05-12",
  },
  {
    id: "reg-014",
    market: "CN",
    title: "强制性产品认证 CCC 锂电池适用范围提示",
    titleEn: "CCC Applicability Reminder for Lithium Batteries",
    publishDate: "2026-04-30",
    effectiveDate: "2026-08-01",
    affectedCategories: ["锂电池", "电动工具", "移动电源", "消费电子"],
    affectedCategoriesEn: ["Lithium Batteries", "Power Tools", "Power Banks", "Consumer Electronics"],
    summary:
      "中国市场对部分锂电池和移动电源产品的 CCC 适用范围进一步明确，进口、内销和平台入驻资料需要同步调整。",
    summaryEn:
      "China further clarifies CCC applicability for certain lithium batteries and power banks; import, domestic sale, and platform onboarding documents should align.",
    sourceAgency: "国家市场监督管理总局",
    sourceAgencyEn: "State Administration for Market Regulation",
    sourceUrl: "https://www.samr.gov.cn/",
    riskLevel: "high",
    changeType: "revision",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "未取得 CCC 或型号覆盖不足的产品可能无法上架国内平台或完成进口清关。",
    businessImpactEn:
      "Products without CCC or insufficient model coverage may be blocked from domestic marketplaces or import clearance.",
    requirements: ["确认 CCC 目录适用性", "证书覆盖所有型号", "中文铭牌和说明书齐备"],
    requirementsEn: ["Confirm CCC catalog applicability", "Certificate covers all models", "Chinese nameplate and manual are ready"],
    recommendedActions: ["建立型号差异表", "预约 CCC 工厂检查准备", "核对国内平台资质字段"],
    recommendedActionsEn: [
      "Create a model-difference table",
      "Prepare for CCC factory inspection",
      "Check domestic marketplace qualification fields",
    ],
    lastVerifiedAt: "2026-05-18",
  },
  {
    id: "reg-015",
    market: "AU",
    title: "纽扣电池安全标准执法复核",
    titleEn: "Button and Coin Battery Safety Enforcement Review",
    publishDate: "2026-04-22",
    effectiveDate: "2026-05-30",
    affectedCategories: ["遥控器", "玩具", "LED 灯具", "小型电子"],
    affectedCategoriesEn: ["Remote Controls", "Toys", "LED Lights", "Small Electronics"],
    summary:
      "澳大利亚继续重点检查含纽扣电池产品的电池仓安全、警示标签和儿童防护设计，线上卖家需要保留测试证据。",
    summaryEn:
      "Australia continues priority checks on button/coin battery compartment security, warning labels, and child-resistant design; online sellers need retained test evidence.",
    sourceAgency: "ACCC Product Safety Australia",
    sourceAgencyEn: "ACCC Product Safety Australia",
    sourceUrl: "https://www.productsafety.gov.au/product-safety-laws/safety-standards-bans/mandatory-standards/button-and-coin-batteries",
    riskLevel: "critical",
    changeType: "enforcement",
    status: "立即处理",
    statusEn: "Immediate action",
    businessImpact: "未满足电池仓和警示要求的产品有高下架和召回风险，尤其是玩具和家用小电子。",
    businessImpactEn:
      "Products failing battery compartment and warning requirements face high takedown and recall risk, especially toys and small household electronics.",
    requirements: ["电池仓需工具开启或双动作开启", "包装和说明书有吞咽警示", "测试报告覆盖最终销售状态"],
    requirementsEn: [
      "Battery compartment requires tool or dual-action opening",
      "Packaging and manuals include ingestion warnings",
      "Test report covers final sale configuration",
    ],
    recommendedActions: ["立即冻结高风险新品发布", "抽检含纽扣电池库存", "更新图片和页面警示"],
    recommendedActionsEn: [
      "Pause high-risk new launches immediately",
      "Inspect inventory containing button batteries",
      "Update images and page warnings",
    ],
    lastVerifiedAt: "2026-05-21",
  },
  {
    id: "reg-016",
    market: "AE",
    title: "阿联酋 RoHS 有害物质符合性文件抽查",
    titleEn: "UAE RoHS Hazardous Substance Compliance File Checks",
    publishDate: "2026-04-02",
    effectiveDate: "2026-07-10",
    affectedCategories: ["电子电器", "照明", "IT 设备", "电动工具"],
    affectedCategoriesEn: ["Electronics", "Lighting", "IT Equipment", "Power Tools"],
    summary:
      "阿联酋对电子电器产品 RoHS 技术文件进行更频繁抽查，材料声明、测试报告和 ECAS 证书需要相互对应。",
    summaryEn:
      "The UAE increases spot checks on RoHS technical files for electrical products; material declarations, test reports, and ECAS certificates should align.",
    sourceAgency: "MoIAT / UAE RoHS",
    sourceAgencyEn: "MoIAT / UAE RoHS",
    sourceUrl: "https://moiat.gov.ae/",
    riskLevel: "high",
    changeType: "enforcement",
    status: "重点抽查",
    statusEn: "Priority screening",
    businessImpact: "如果 RoHS 文件无法按型号追溯，进口商可能要求延迟出货或重新认证。",
    businessImpactEn:
      "If RoHS files cannot be traced by model, importers may request shipment delays or recertification.",
    requirements: ["RoHS 报告按型号归档", "材料声明与 BOM 一致", "ECAS 证书状态有效"],
    requirementsEn: ["RoHS reports filed by model", "Material declarations align with BOM", "ECAS certificate remains valid"],
    recommendedActions: ["对中东 SKU 做文件体检", "把 RoHS 报告接入证书台账", "更新供应商承诺函"],
    recommendedActionsEn: [
      "Audit Middle East SKU documentation",
      "Link RoHS reports to certificate register",
      "Refresh supplier commitment letters",
    ],
    lastVerifiedAt: "2026-05-16",
  },
  {
    id: "reg-017",
    market: "SA",
    title: "沙特纺织品标签和 SALEEM 类目规则更新",
    titleEn: "Saudi Textile Labeling and SALEEM Category Rule Update",
    publishDate: "2026-04-01",
    effectiveDate: "2026-10-15",
    affectedCategories: ["服装", "家纺", "鞋类", "儿童纺织品"],
    affectedCategoriesEn: ["Apparel", "Home Textiles", "Footwear", "Children's Textiles"],
    summary:
      "沙特更新部分纺织品标签、阿拉伯语信息和 SALEEM 类目规则。纤维成分、原产地和护理说明需要符合本地格式。",
    summaryEn:
      "Saudi Arabia updates textile labeling, Arabic information, and SALEEM category rules. Fiber content, origin, and care instructions need local-format compliance.",
    sourceAgency: "SASO",
    sourceAgencyEn: "SASO",
    sourceUrl: "https://www.saso.gov.sa/",
    riskLevel: "medium",
    changeType: "revision",
    status: "过渡期",
    statusEn: "Transition period",
    businessImpact: "标签返工会影响服装类目大促备货，阿拉伯语翻译错误也可能造成证书退回。",
    businessImpactEn:
      "Label rework can affect apparel promotion stock planning; Arabic translation errors may also cause certificate rejection.",
    requirements: ["阿拉伯语标签准确", "纤维成分百分比完整", "护理符号符合要求"],
    requirementsEn: ["Arabic labels are accurate", "Fiber percentages are complete", "Care symbols meet requirements"],
    recommendedActions: ["建立沙特标签模板", "抽查供应商吊牌", "复核 SALEEM 类目选择"],
    recommendedActionsEn: [
      "Build Saudi label templates",
      "Spot-check supplier hangtags",
      "Review SALEEM category selection",
    ],
    lastVerifiedAt: "2026-05-11",
  },
  {
    id: "reg-018",
    market: "CA",
    title: "加拿大消费品事故报告时限提醒",
    titleEn: "Canada Consumer Product Incident Reporting Timeline Reminder",
    publishDate: "2026-04-12",
    effectiveDate: "2026-06-30",
    affectedCategories: ["消费品", "儿童用品", "运动户外", "家居用品"],
    affectedCategoriesEn: ["Consumer Goods", "Children's Products", "Sports & Outdoors", "Home Goods"],
    summary:
      "加拿大消费品安全法下，企业获知重大事故、缺陷或召回信息后需要按规定时限向监管机构报告。",
    summaryEn:
      "Under the Canada Consumer Product Safety Act, companies must report serious incidents, defects, or recall information to regulators within required timelines.",
    sourceAgency: "加拿大卫生部 Health Canada",
    sourceAgencyEn: "Health Canada",
    sourceUrl: "https://www.canada.ca/en/health-canada/services/consumer-product-safety.html",
    riskLevel: "high",
    changeType: "enforcement",
    status: "持续有效",
    statusEn: "In force",
    businessImpact: "客服、质检和合规团队如果没有共享事故信息，可能错过报告时限并产生执法风险。",
    businessImpactEn:
      "If customer service, quality, and compliance teams do not share incident information, reporting deadlines may be missed.",
    requirements: ["建立事故判定标准", "保留投诉和维修记录", "按时提交监管报告"],
    requirementsEn: ["Define incident triage criteria", "Keep complaint and repair records", "Submit regulatory reports on time"],
    recommendedActions: ["配置加拿大事故升级流程", "训练客服识别伤害关键词", "每月复核投诉闭环"],
    recommendedActionsEn: [
      "Configure Canada incident escalation",
      "Train support teams on injury keywords",
      "Review complaint closure monthly",
    ],
    lastVerifiedAt: "2026-05-15",
  },
  {
    id: "reg-019",
    market: "CA",
    title: "ISED 无线设备标准和标签文件更新",
    titleEn: "ISED Radio Equipment Standard and Label File Update",
    publishDate: "2026-03-31",
    effectiveDate: "2026-09-01",
    affectedCategories: ["蓝牙设备", "Wi-Fi 设备", "智能家居", "遥控器"],
    affectedCategoriesEn: ["Bluetooth Devices", "Wi-Fi Devices", "Smart Home", "Remote Controls"],
    summary:
      "加拿大无线设备认证要求更新，模块认证、主机标签和用户手册中的合规声明需要保持一致。",
    summaryEn:
      "Canada updates radio equipment certification expectations; module approval, host labels, and user manual compliance statements should remain consistent.",
    sourceAgency: "加拿大创新、科学与经济发展部 ISED",
    sourceAgencyEn: "Innovation, Science and Economic Development Canada (ISED)",
    sourceUrl: "https://ised-isde.canada.ca/site/certification-engineering-bureau/en",
    riskLevel: "medium",
    changeType: "revision",
    status: "草案跟踪",
    statusEn: "Draft monitored",
    businessImpact: "无线模块替换或天线差异可能触发补测，影响北美共用库存策略。",
    businessImpactEn:
      "Wireless module changes or antenna differences may trigger retesting, affecting shared North America inventory strategies.",
    requirements: ["ISED ID 标识正确", "模块使用条件满足", "英文/法文声明完整"],
    requirementsEn: ["ISED ID marking is correct", "Module use conditions are met", "English/French statements are complete"],
    recommendedActions: ["复核无线模块 AVL", "检查加拿大标签版式", "同步 FCC/ISED 文件差异"],
    recommendedActionsEn: [
      "Review wireless module AVL",
      "Check Canada label artwork",
      "Align FCC/ISED dossier differences",
    ],
    lastVerifiedAt: "2026-05-10",
  },
  {
    id: "reg-020",
    market: "KR",
    title: "韩国 KC 锂电池和充电产品安全确认更新",
    titleEn: "Korea KC Safety Confirmation Update for Batteries and Chargers",
    publishDate: "2026-04-26",
    effectiveDate: "2026-07-25",
    affectedCategories: ["锂电池", "充电器", "小家电", "消费电子"],
    affectedCategoriesEn: ["Lithium Batteries", "Chargers", "Small Appliances", "Consumer Electronics"],
    summary:
      "韩国对部分锂电池和充电产品的 KC 安全确认资料提出更细的型号覆盖和标签要求。",
    summaryEn:
      "Korea adds more granular model coverage and marking expectations for KC safety confirmation on certain batteries and charging products.",
    sourceAgency: "韩国产业通商资源部 MOTIE",
    sourceAgencyEn: "Korea Ministry of Trade, Industry and Energy (MOTIE)",
    sourceUrl: "https://www.motie.go.kr/eng/",
    riskLevel: "high",
    changeType: "revision",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "韩语标签、证书型号和实际销售套装不一致时，平台审核和进口通关会受影响。",
    businessImpactEn:
      "Mismatch between Korean labels, certificate models, and actual bundles can affect marketplace review and import clearance.",
    requirements: ["KC 证书覆盖销售套装", "韩语标签和警示完整", "电池运输文件齐备"],
    requirementsEn: ["KC certificate covers sale bundle", "Korean labels and warnings are complete", "Battery transport files are ready"],
    recommendedActions: ["拆分单品和套装认证状态", "检查韩语说明书", "复核进口商信息"],
    recommendedActionsEn: [
      "Separate certification status for single items and bundles",
      "Check Korean manuals",
      "Review importer information",
    ],
    lastVerifiedAt: "2026-05-18",
  },
  {
    id: "reg-021",
    market: "KR",
    title: "K-REACH 化学物质登记和下游用户信息传递",
    titleEn: "K-REACH Registration and Downstream User Communication",
    publishDate: "2026-03-22",
    effectiveDate: "2026-12-31",
    affectedCategories: ["化学品", "涂料", "胶黏剂", "塑料制品"],
    affectedCategoriesEn: ["Chemicals", "Coatings", "Adhesives", "Plastic Products"],
    summary:
      "韩国 K-REACH 对进口化学物质登记、吨位确认和下游用户信息传递持续加强，含化学混合物产品需要供应链配合。",
    summaryEn:
      "K-REACH continues strengthening imported chemical registration, tonnage confirmation, and downstream user communication; products with chemical mixtures need supply-chain coordination.",
    sourceAgency: "韩国环境部",
    sourceAgencyEn: "Korea Ministry of Environment",
    sourceUrl: "https://eng.me.go.kr/",
    riskLevel: "medium",
    changeType: "revision",
    status: "过渡期",
    statusEn: "Transition period",
    businessImpact: "化学品或含胶黏剂产品若缺少成分信息，韩国经销商可能要求暂停销售。",
    businessImpactEn:
      "Chemical products or goods with adhesives may be paused by Korean distributors if composition information is missing.",
    requirements: ["确认进口吨位", "保留 SDS 和成分声明", "下游用户用途信息可追溯"],
    requirementsEn: ["Confirm import tonnage", "Keep SDS and composition statements", "Trace downstream use information"],
    recommendedActions: ["向供应商补采韩规 SDS", "建立化学品吨位台账", "识别需要 OR 代表的情形"],
    recommendedActionsEn: [
      "Collect Korea-format SDS from suppliers",
      "Create chemical tonnage register",
      "Identify cases requiring an OR representative",
    ],
    lastVerifiedAt: "2026-05-09",
  },
  {
    id: "reg-022",
    market: "IN",
    title: "印度 BIS CRS 电子产品目录扩展",
    titleEn: "India BIS CRS Electronics Product Scope Expansion",
    publishDate: "2026-04-16",
    effectiveDate: "2026-08-10",
    affectedCategories: ["IT 设备", "电源适配器", "智能设备", "音视频产品"],
    affectedCategoriesEn: ["IT Equipment", "Power Adapters", "Smart Devices", "Audio/Video Products"],
    summary:
      "印度 BIS CRS 目录扩展，更多电子产品需要在印度认可实验室完成测试并取得注册号后方可销售。",
    summaryEn:
      "India expands the BIS CRS scope, requiring more electronics to complete testing at recognized Indian labs and obtain registration before sale.",
    sourceAgency: "印度标准局 BIS",
    sourceAgencyEn: "Bureau of Indian Standards (BIS)",
    sourceUrl: "https://www.bis.gov.in/",
    riskLevel: "high",
    changeType: "new",
    status: "已发布",
    statusEn: "Published",
    businessImpact: "测试排期、印度当地代表和标签注册号会影响印度市场首发时间。",
    businessImpactEn:
      "Testing slots, local representative setup, and registration-number labels can affect India launch timing.",
    requirements: ["确认 CRS 目录适用性", "印度实验室测试完成", "标签展示 BIS 注册号"],
    requirementsEn: ["Confirm CRS scope applicability", "Complete testing at Indian lab", "Display BIS registration number on label"],
    recommendedActions: ["优先评估印度热销电子 SKU", "预约 BIS 实验室", "准备本地授权代表资料"],
    recommendedActionsEn: [
      "Prioritize India best-selling electronic SKUs",
      "Book BIS lab slots",
      "Prepare local authorized representative files",
    ],
    lastVerifiedAt: "2026-05-17",
  },
  {
    id: "reg-023",
    market: "IN",
    title: "印度电子废弃物 EPR 门户季度申报提醒",
    titleEn: "India E-Waste EPR Portal Quarterly Return Reminder",
    publishDate: "2026-04-08",
    effectiveDate: "2026-06-30",
    affectedCategories: ["电子电器", "电池产品", "IT 设备", "家电"],
    affectedCategoriesEn: ["Electronics", "Battery Products", "IT Equipment", "Home Appliances"],
    summary:
      "印度电子废弃物规则要求生产者责任延伸 EPR 门户定期申报销售量、回收量和授权回收伙伴信息。",
    summaryEn:
      "India e-waste rules require EPR portal returns covering sales volume, collection volume, and authorized recycler information.",
    sourceAgency: "印度中央污染控制委员会 CPCB",
    sourceAgencyEn: "Central Pollution Control Board (CPCB)",
    sourceUrl: "https://cpcb.nic.in/",
    riskLevel: "high",
    changeType: "enforcement",
    status: "申报期临近",
    statusEn: "Filing window approaching",
    businessImpact: "未按期申报可能影响 EPR 授权状态，进而影响平台资质审核和进口商合作。",
    businessImpactEn:
      "Late returns may affect EPR authorization status, marketplace qualification review, and importer cooperation.",
    requirements: ["维护销售量数据", "上传回收凭证", "确认授权回收商信息"],
    requirementsEn: ["Maintain sales-volume data", "Upload collection evidence", "Confirm authorized recycler details"],
    recommendedActions: ["打通订单数据和 EPR 申报口径", "月度核对回收凭证", "设置季度申报提醒"],
    recommendedActionsEn: [
      "Align order data with EPR return logic",
      "Reconcile collection evidence monthly",
      "Set quarterly filing reminders",
    ],
    lastVerifiedAt: "2026-05-19",
  },
  {
    id: "reg-024",
    market: "EU",
    title: "欧盟电池法规数字电池护照准备要求",
    titleEn: "EU Battery Regulation Digital Battery Passport Preparation",
    publishDate: "2026-03-19",
    effectiveDate: "2027-02-18",
    affectedCategories: ["动力电池", "便携式电池", "含电池设备", "储能产品"],
    affectedCategoriesEn: ["Traction Batteries", "Portable Batteries", "Battery-Containing Devices", "Energy Storage"],
    summary:
      "欧盟电池法规对碳足迹、回收含量、供应链尽责和数字电池护照提出分阶段要求，含电池产品需要提前整理数据。",
    summaryEn:
      "The EU Battery Regulation phases in carbon footprint, recycled content, due diligence, and digital battery passport requirements; battery-containing products should prepare data early.",
    sourceAgency: "欧盟委员会",
    sourceAgencyEn: "European Commission",
    sourceUrl: "https://environment.ec.europa.eu/topics/waste-and-recycling/batteries_en",
    riskLevel: "medium",
    changeType: "new",
    status: "分阶段实施",
    statusEn: "Phased implementation",
    businessImpact: "电池供应链数据颗粒度不足会影响未来欧盟上架和 B2B 客户准入。",
    businessImpactEn:
      "Insufficient battery supply-chain data granularity can affect future EU listing and B2B customer access.",
    requirements: ["收集电池材料和碳足迹数据", "准备尽责管理信息", "规划二维码和护照数据字段"],
    requirementsEn: [
      "Collect battery material and carbon-footprint data",
      "Prepare due-diligence information",
      "Plan QR code and passport data fields",
    ],
    recommendedActions: ["提前对接电芯供应商", "梳理电池 BOM 数据", "设计护照字段数据模型"],
    recommendedActionsEn: [
      "Engage cell suppliers early",
      "Map battery BOM data",
      "Design passport field data model",
    ],
    lastVerifiedAt: "2026-05-08",
  },
  {
    id: "reg-025",
    market: "EU",
    title: "ESPR 可持续产品生态设计和数字产品护照草案",
    titleEn: "ESPR Ecodesign and Digital Product Passport Draft",
    publishDate: "2026-03-12",
    effectiveDate: "2026-12-01",
    affectedCategories: ["纺织品", "家具", "电子电器", "家居用品"],
    affectedCategoriesEn: ["Textiles", "Furniture", "Electronics", "Home Goods"],
    summary:
      "欧盟可持续产品生态设计框架推进数字产品护照、可维修性和可持续信息披露要求，先行类目需要准备数据治理。",
    summaryEn:
      "The EU Ecodesign for Sustainable Products framework advances digital product passport, repairability, and sustainability disclosure requirements for priority categories.",
    sourceAgency: "欧盟委员会",
    sourceAgencyEn: "European Commission",
    sourceUrl: "https://commission.europa.eu/energy-climate-change-environment/standards-tools-and-labels/products-labelling-rules-and-requirements/sustainable-products/ecodesign-sustainable-products-regulation_en",
    riskLevel: "medium",
    changeType: "consultation",
    status: "公开咨询",
    statusEn: "Public consultation",
    businessImpact: "产品主数据、物料来源和维修备件信息将成为欧盟渠道准入和大客户审核重点。",
    businessImpactEn:
      "Product master data, material origin, and spare-part information will become key EU channel and enterprise-customer review points.",
    requirements: ["梳理产品可持续属性", "准备维修和备件信息", "评估数字产品护照字段"],
    requirementsEn: [
      "Map product sustainability attributes",
      "Prepare repair and spare-part information",
      "Assess digital product passport fields",
    ],
    recommendedActions: ["选择 3 个试点类目", "建立产品环境数据字典", "同步设计和采购团队"],
    recommendedActionsEn: [
      "Select three pilot categories",
      "Create product environmental data dictionary",
      "Align design and procurement teams",
    ],
    lastVerifiedAt: "2026-05-07",
  },
  {
    id: "reg-026",
    market: "UK",
    title: "OPSS 产品安全事件和召回协作要求",
    titleEn: "OPSS Product Safety Incident and Recall Coordination Requirements",
    publishDate: "2026-05-01",
    effectiveDate: "2026-07-20",
    affectedCategories: ["消费品", "玩具", "电子电器", "家居用品"],
    affectedCategoriesEn: ["Consumer Goods", "Toys", "Electronics", "Home Goods"],
    summary:
      "英国 OPSS 强调企业发现产品安全事件后的信息留存、风险评估和召回协作义务，线上卖家需要可快速提供销售记录。",
    summaryEn:
      "The UK OPSS emphasizes recordkeeping, risk assessment, and recall cooperation obligations after product safety incidents; online sellers need rapid access to sales records.",
    sourceAgency: "英国 Office for Product Safety and Standards",
    sourceAgencyEn: "UK Office for Product Safety and Standards",
    sourceUrl: "https://www.gov.uk/government/organisations/office-for-product-safety-and-standards",
    riskLevel: "high",
    changeType: "enforcement",
    status: "重点抽查",
    statusEn: "Priority screening",
    businessImpact: "缺少销售去向、批次和事故处理记录会增加召回成本，并影响英国渠道合作。",
    businessImpactEn:
      "Missing sales destination, batch, or incident handling records can increase recall cost and affect UK channel relationships.",
    requirements: ["保留批次和销售记录", "建立风险评估流程", "准备召回沟通材料"],
    requirementsEn: ["Keep batch and sales records", "Set up risk assessment workflow", "Prepare recall communication materials"],
    recommendedActions: ["把英国订单纳入批次追溯", "建立 OPSS 事件模板", "演练召回审批链"],
    recommendedActionsEn: [
      "Add UK orders to batch traceability",
      "Create OPSS incident templates",
      "Rehearse recall approval chain",
    ],
    lastVerifiedAt: "2026-05-20",
  },
  {
    id: "reg-027",
    market: "BR",
    title: "ANATEL CPE 网络安全测试要求跟踪",
    titleEn: "ANATEL Cybersecurity Testing Requirements for CPE",
    publishDate: "2026-03-15",
    effectiveDate: "2026-11-30",
    affectedCategories: ["路由器", "IoT 设备", "网关", "无线通信设备"],
    affectedCategoriesEn: ["Routers", "IoT Devices", "Gateways", "Wireless Communication Devices"],
    summary:
      "巴西 ANATEL 对通信终端设备的网络安全测试、默认密码和固件更新机制提出更高要求。",
    summaryEn:
      "Brazil ANATEL raises expectations for cybersecurity testing, default passwords, and firmware update mechanisms for customer premises and connected devices.",
    sourceAgency: "巴西国家电信局 ANATEL",
    sourceAgencyEn: "Brazil National Telecommunications Agency (ANATEL)",
    sourceUrl: "https://www.gov.br/anatel/",
    riskLevel: "medium",
    changeType: "revision",
    status: "草案跟踪",
    statusEn: "Draft monitored",
    businessImpact: "IoT 产品可能需要补充固件安全说明和漏洞响应流程，认证周期会拉长。",
    businessImpactEn:
      "IoT products may need additional firmware security documentation and vulnerability response processes, extending certification timelines.",
    requirements: ["默认密码策略合规", "固件更新机制说明", "漏洞响应联系人明确"],
    requirementsEn: ["Compliant default password policy", "Firmware update mechanism documented", "Vulnerability response contact defined"],
    recommendedActions: ["让研发输出安全白皮书", "检查默认账号策略", "准备 OTA 更新证据"],
    recommendedActionsEn: [
      "Have engineering prepare a security brief",
      "Check default account policy",
      "Prepare OTA update evidence",
    ],
    lastVerifiedAt: "2026-05-06",
  },
  {
    id: "reg-028",
    market: "US",
    title: "FCC 网络安全标签计划试点跟踪",
    titleEn: "FCC Cyber Trust Mark Pilot Monitoring",
    publishDate: "2026-03-20",
    effectiveDate: "2026-09-30",
    affectedCategories: ["IoT 设备", "智能家居", "路由器", "摄像头"],
    affectedCategoriesEn: ["IoT Devices", "Smart Home", "Routers", "Cameras"],
    summary:
      "FCC 网络安全标签计划推进 IoT 产品安全声明、漏洞披露和更新支持周期透明化，智能硬件品牌可提前准备自愿认证资料。",
    summaryEn:
      "The FCC Cyber Trust Mark program advances IoT security declarations, vulnerability disclosure, and update-support transparency; smart hardware brands can prepare voluntary certification files early.",
    sourceAgency: "美国联邦通信委员会 FCC",
    sourceAgencyEn: "Federal Communications Commission (FCC)",
    sourceUrl: "https://www.fcc.gov/cybersecurity-certification-mark",
    riskLevel: "medium",
    changeType: "consultation",
    status: "试点跟踪",
    statusEn: "Pilot monitored",
    businessImpact: "网络安全标签可能成为智能家居产品的渠道加分项，也会影响企业客户采购门槛。",
    businessImpactEn:
      "Cybersecurity labeling may become a channel differentiator for smart-home products and affect enterprise purchasing thresholds.",
    requirements: ["公开安全更新支持期", "建立漏洞披露渠道", "保留安全测试证据"],
    requirementsEn: ["Disclose security update support period", "Set up vulnerability disclosure channel", "Retain security test evidence"],
    recommendedActions: ["整理 IoT 安全控制清单", "定义固件支持政策", "评估是否参与自愿标签"],
    recommendedActionsEn: [
      "Compile IoT security control checklist",
      "Define firmware support policy",
      "Assess voluntary label participation",
    ],
    lastVerifiedAt: "2026-05-05",
  },
  {
    id: "reg-029",
    market: "CN",
    title: "玩具安全国家标准化学迁移限量复核",
    titleEn: "China Toy Safety Standard Chemical Migration Limit Review",
    publishDate: "2026-03-18",
    effectiveDate: "2026-11-01",
    affectedCategories: ["玩具", "儿童饰品", "文具", "儿童家具"],
    affectedCategoriesEn: ["Toys", "Children's Accessories", "Stationery", "Children's Furniture"],
    summary:
      "中国玩具安全标准复核部分化学迁移限量和年龄警示标识要求，含涂层、软胶和儿童可接触部件的产品需要重点关注。",
    summaryEn:
      "China reviews chemical migration limits and age warning label requirements in toy safety standards, especially for coatings, soft plastics, and child-accessible parts.",
    sourceAgency: "国家标准化管理委员会",
    sourceAgencyEn: "Standardization Administration of China",
    sourceUrl: "https://www.sac.gov.cn/",
    riskLevel: "medium",
    changeType: "consultation",
    status: "公开征求意见",
    statusEn: "Public consultation",
    businessImpact: "儿童类产品设计和材料替换周期较长，若等到正式实施再调整，容易错过销售季。",
    businessImpactEn:
      "Children's products have longer design and material substitution cycles; waiting for final adoption may miss seasonal sales windows.",
    requirements: ["复核年龄分级", "检查涂层和软胶材料", "中文警示标签完整"],
    requirementsEn: ["Review age grading", "Check coatings and soft plastics", "Complete Chinese warning labels"],
    recommendedActions: ["提前评估高风险材料", "把供应商材料锁定到批次", "准备中文标签改版"],
    recommendedActionsEn: [
      "Assess high-risk materials early",
      "Lock supplier materials to batches",
      "Prepare Chinese label revisions",
    ],
    lastVerifiedAt: "2026-05-04",
  },
  {
    id: "reg-030",
    market: "EU",
    title: "包装和包装废弃物法规 PPWR 实施准备",
    titleEn: "EU Packaging and Packaging Waste Regulation Preparation",
    publishDate: "2026-03-08",
    effectiveDate: "2026-12-31",
    affectedCategories: ["包装", "电商发货", "消费品", "食品接触材料"],
    affectedCategoriesEn: ["Packaging", "E-Commerce Fulfillment", "Consumer Goods", "Food Contact Materials"],
    summary:
      "欧盟包装法规推动包装减量、可回收设计和标签一致性。跨境电商品牌需要同步评估商品包装和物流包装。",
    summaryEn:
      "EU packaging rules push packaging reduction, recyclable design, and labeling consistency. Cross-border brands should assess both product packaging and shipping packaging.",
    sourceAgency: "欧盟委员会",
    sourceAgencyEn: "European Commission",
    sourceUrl: "https://environment.ec.europa.eu/topics/waste-and-recycling/packaging-waste_en",
    riskLevel: "medium",
    changeType: "new",
    status: "分阶段实施",
    statusEn: "Phased implementation",
    businessImpact: "包装材料、EPR 成本和多语言回收标签会影响毛利和仓配作业。",
    businessImpactEn:
      "Packaging materials, EPR cost, and multilingual recycling labels can affect gross margin and fulfillment operations.",
    requirements: ["梳理包装材料组成", "评估可回收性声明", "同步 EPR 注册和申报"],
    requirementsEn: ["Map packaging material composition", "Assess recyclability claims", "Align EPR registration and returns"],
    recommendedActions: ["减少二次包装", "统一欧盟回收标签", "把包装重量接入利润模型"],
    recommendedActionsEn: [
      "Reduce secondary packaging",
      "Standardize EU recycling labels",
      "Feed packaging weight into profit model",
    ],
    lastVerifiedAt: "2026-05-03",
  },
];
