"""Replaceable infrastructure ports used by scan application services."""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol

from rag_service.domain.scans import ScanJob, ScanSession, StoredUpload, UploadKind


ScanRunner = Callable[[dict[str, Any]], Awaitable[dict[str, Any]]]


class ScanBackend(Protocol):
    def save_session(self, session: ScanSession) -> None: ...
    def get_session(self, session_id: str) -> ScanSession | None: ...
    def delete_session(self, session_id: str) -> None: ...
    def save_upload(
        self,
        session_id: str,
        kind: UploadKind,
        original_name: str,
        content_type: str,
        content: bytes,
    ) -> StoredUpload: ...
    def list_uploads(self, session_id: str) -> list[StoredUpload]: ...
    def save_job(self, job: ScanJob) -> None: ...
    def get_job(self, job_id: str) -> ScanJob | None: ...
    def delete_job(self, job_id: str) -> None: ...
    def claim_job(self, job_id: str) -> ScanJob: ...
    def list_recoverable_jobs(self) -> list[ScanJob]: ...
    def append_audit(self, event: dict[str, Any]) -> None: ...
