"""Replaceable infrastructure ports used by scan application services."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Awaitable, Callable, Protocol

from rag_service.domain.scans import ScanJob, ScanSession, StoredUpload, UploadKind


ScanRunner = Callable[[dict[str, Any]], Awaitable[dict[str, Any]]]


class ScanBackend(Protocol):
    def save_session(self, session: ScanSession) -> None: ...
    def get_session(self, session_id: str) -> ScanSession | None: ...
    def delete_session(self, session_id: str) -> None: ...
    def purge_expired_sessions(self, now: datetime | None = None) -> int: ...
    def save_upload(
        self,
        session_id: str,
        kind: UploadKind,
        original_name: str,
        content_type: str,
        content: bytes,
    ) -> StoredUpload: ...
    def list_uploads(self, session_id: str) -> list[StoredUpload]: ...
    def get_upload(self, session_id: str, upload_id: str) -> StoredUpload | None: ...
    def read_upload(self, session_id: str, upload_id: str) -> tuple[StoredUpload, bytes]: ...
    def save_job(self, job: ScanJob) -> None: ...
    def get_job(self, job_id: str) -> ScanJob | None: ...
    def delete_job(self, job_id: str) -> None: ...
    def claim_job(self, job_id: str, *, lease_seconds: int) -> ScanJob | None: ...
    def renew_job_lease(self, job_id: str, *, lease_seconds: int) -> bool: ...
    def list_recoverable_jobs(self) -> list[ScanJob]: ...
    def list_pending_retry_jobs(self) -> list[ScanJob]: ...
    def append_audit(self, event: dict[str, Any]) -> None: ...
