#!/usr/bin/env python3
"""
anchor_selection.py - Cap the generated full-library anchors per scan.

2026-09-19 full-library integration: every catalog regulation now has a KB
anchor (curation: auto, generated by scripts/generate_kb_anchors.py). A
category x market scan can match hundreds of them (US alone holds 300+
electronics-domain CFR entries), which would blow both the prompt budget
and the report's output budget. This module keeps the *curated* anchors
(the hand-authored 61, curation absent) untouched and selects a bounded,
deterministically-ranked subset of the generated ones.

Ranking is deterministic and LLM-free: product-token overlap with the
regulation's title wins, then shorter ids, so the same scan always gets
the same selection.
"""
from __future__ import annotations

import re

# 生成的品类/特征锚点：每次扫描最多纳入数
MAX_GENERATED_CATEGORY = 12
# 生成的市场级横切锚点：每个目标市场最多纳入数
MAX_GENERATED_MARKET_PER_MARKET = 3
# 生成的 GLOBAL/UN 锚点（随 ALWAYS_INCLUDE_REGIONS 进入所有扫描）：最多纳入数
MAX_GENERATED_GLOBAL = 3
# 生成锚点的条款正文进入 prompt 的预算（字符）；超预算的部分丢弃
GENERATED_ARTICLE_BUDGET_CHARS = 40_000
# 生成锚点单条条款正文进入 prompt 的上限
GENERATED_ARTICLE_MAX_CHARS = 2_500

# 市场级横切领域的排序优先级：产品合规贴近的领域排前，纯商业/金融监管排后。
# 未列出的领域按列表长度（最低优先级）处理。
MARKET_DOMAIN_PRIORITY = (
    "消费者保护", "产品安全", "产品认证", "技术标准", "市场监督",
    "数据保护", "网络安全", "环境", "能源", "知识产权", "商标专利",
    "医疗器械", "电信", "电商平台", "海关商贸", "海关税务", "出口管制",
    "反垄断", "税务", "汽车网络安全", "投资准入", "劳动法", "金融支付", "支付服务",
)

# 品类排序关键词：标题命中加分（英文法规标题 vs 中文产品名的桥接）
CATEGORY_TITLE_KEYWORDS = {
    "electronics": ("electronic", "electrical", "radio", "emc", "telecommunication",
                    "information technology", "电子", "电器", "无线", "信息技术"),
    "toy": ("toy", "children's product", "child", "玩具", "儿童"),
    "battery": ("battery", "lithium", "cell", "电池", "锂"),
    "textile": ("textile", "fibre", "fiber", "clothing", "apparel", "纺织", "服装", "纤维"),
    "cosmetic": ("cosmetic", "化妆品"),
    "food_contact": ("food contact", "food", "食品"),
    "appliance": ("appliance", "household", "家电", "家用", "器具"),
    "3c": ("information technology", "radio", "communication", "计算机", "通信"),
    "home": ("furniture", "household", "home", "家具", "家居"),
    "other": (),
}


def _tokenize(text: str) -> set[str]:
    """Lowercased word tokens; CJK text becomes 2-char grams."""
    text = (text or "").lower()
    tokens = set(re.findall(r"[a-z0-9][a-z0-9_-]{1,}", text))
    cjk = re.findall(r"[一-鿿]", text)
    tokens.update(cjk[i] + cjk[i + 1] for i in range(len(cjk) - 1))
    return tokens


def _title_score(anchor: dict, product_tokens: set[str]) -> int:
    if not product_tokens:
        return 0
    title_tokens = _tokenize(
        f"{anchor.get('short_name') or ''} {anchor.get('doc_name') or ''}"
    )
    return len(title_tokens & product_tokens)


def _category_keyword_score(anchor: dict, category: str) -> int:
    keywords = CATEGORY_TITLE_KEYWORDS.get(category, ())
    if not keywords:
        return 0
    title = f"{anchor.get('short_name') or ''} {anchor.get('doc_name') or ''}".lower()
    return sum(1 for kw in keywords if kw in title)


def _market_domain_rank(anchor: dict) -> int:
    try:
        return MARKET_DOMAIN_PRIORITY.index(str(anchor.get("domain") or ""))
    except ValueError:
        return len(MARKET_DOMAIN_PRIORITY)


def _rank(anchors: list[dict], product: str, category: str = "") -> list[dict]:
    product_tokens = _tokenize(product)
    return sorted(
        anchors,
        key=lambda a: (
            -_title_score(a, product_tokens),
            -_category_keyword_score(a, category),
            str(a.get("regulation_id") or ""),
        ),
    )


def _rank_market(anchors: list[dict], product: str) -> list[dict]:
    product_tokens = _tokenize(product)
    return sorted(
        anchors,
        key=lambda a: (
            -_title_score(a, product_tokens),
            _market_domain_rank(a),
            str(a.get("regulation_id") or ""),
        ),
    )


def bound_anchor_set(
    anchors: list[dict],
    product: str = "",
    category: str = "",
) -> tuple[list[dict], dict]:
    """Split curated vs generated anchors and cap the generated side.

    Returns (bounded_list, stats). The input list is never mutated; curated
    anchors keep their original relative order, selected generated anchors
    are appended after them.
    """
    curated = [a for a in anchors if str(a.get("curation") or "") != "auto"]
    generated = [a for a in anchors if str(a.get("curation") or "") == "auto"]

    if not generated:
        return list(anchors), {
            "curated": len(curated),
            "generated_available": 0,
            "generated_selected": 0,
        }

    global_pool: list[dict] = []
    market_pools: dict[str, list[dict]] = {}
    category_pool: list[dict] = []
    for anchor in generated:
        region = str(anchor.get("region") or "").upper()
        source = str(anchor.get("source") or "")
        if region in {"GLOBAL", "UN"}:
            global_pool.append(anchor)
        elif source == "market":
            market_pools.setdefault(region, []).append(anchor)
        else:
            category_pool.append(anchor)

    selected: list[dict] = []
    selected.extend(_rank(category_pool, product, category)[:MAX_GENERATED_CATEGORY])
    for region in sorted(market_pools):
        selected.extend(_rank_market(market_pools[region], product)[:MAX_GENERATED_MARKET_PER_MARKET])
    selected.extend(_rank(global_pool, product, category)[:MAX_GENERATED_GLOBAL])

    return curated + selected, {
        "curated": len(curated),
        "generated_available": len(generated),
        "generated_selected": len(selected),
    }


def bound_generated_article_texts(
    article_texts: dict[str, str],
    anchors: list[dict],
) -> dict[str, str]:
    """Clip the generated anchors' article bodies for the prompt budget.

    Curated anchors keep their full text (existing behavior, already bounded
    by key_articles). Generated anchors are capped per article and dropped
    once the budget is spent, so a 300-CFR-part scan cannot push megabytes
    into the LLM input.
    """
    generated_docs = {
        str(a.get("regulation_id") or "")
        for a in anchors
        if str(a.get("curation") or "") == "auto"
    }
    out: dict[str, str] = {}
    spent = 0
    for key, text in article_texts.items():
        doc_id = str(key).split("#", 1)[0]
        body = str(text or "")
        if doc_id not in generated_docs:
            out[key] = body
            continue
        if spent >= GENERATED_ARTICLE_BUDGET_CHARS:
            continue
        clipped = body[:GENERATED_ARTICLE_MAX_CHARS]
        if len(clipped) < len(body):
            clipped += "\n[条款正文超长，此处截断；完整文本见法规档案]"
        out[key] = clipped
        spent += len(clipped)
    return out


__all__ = [
    "MAX_GENERATED_CATEGORY",
    "MAX_GENERATED_GLOBAL",
    "MAX_GENERATED_MARKET_PER_MARKET",
    "bound_anchor_set",
    "bound_generated_article_texts",
]
