import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const base = process.env.ADMIN_VERIFY_URL || "http://127.0.0.1:3015";
const accessFile = process.env.ADMIN_ACCESS_FILE || ".deploy/admin-access.txt";
const password = readFileSync(accessFile, "utf8").split("\n")[0].split("：")[1];
assert(password, "管理员凭据文件缺少密码");
const request = (pathname, options = {}) => fetch(`${base}${pathname}`, { redirect: "manual", ...options });
const anonymous = await request("/api/admin/overview");
assert.equal(anonymous.status, 401);
const redirect = await request("/admin");
assert.equal(redirect.status, 307);
assert.match(redirect.headers.get("location"), /\/admin\/login$/);
const forged = await request("/api/admin/overview", { headers: { Cookie: "attrax_admin=" + "x".repeat(43) } });
assert.equal(forged.status, 401);
const crossSite = await request("/api/admin/login", { method: "POST", headers: { Origin: "https://example.invalid", "Content-Type": "application/json" }, body: JSON.stringify({ password }) });
assert.equal(crossSite.status, 403);
const badPassword = await request("/api/admin/login", { method: "POST", headers: { Origin: base, "Content-Type": "application/json" }, body: JSON.stringify({ password: "wrong-password-rejected" }) });
assert.equal(badPassword.status, 401);
const login = await request("/api/admin/login", { method: "POST", headers: { Origin: base, "Content-Type": "application/json" }, body: JSON.stringify({ password }) });
assert.equal(login.status, 200, await login.text());
const session = login.headers.get("set-cookie");
assert.match(session, /HttpOnly/i);
assert.match(session, /SameSite=Strict/i);
if (base.startsWith("https:")) assert.match(session, /Secure/i);
const cookie = session.split(";")[0];
const headers = { Cookie: cookie };
const invalidRange = await request("/api/admin/overview?days=999", { headers });
assert.equal(invalidRange.status, 400);
const results = [];
for (const days of [7, 30, 90]) {
  const response = await request(`/api/admin/overview?days=${days}`, { headers });
  assert.equal(response.status, 200, await response.clone().text());
  assert.match(response.headers.get("cache-control"), /no-store/);
  const overview = await response.json();
  assert.equal(overview.series.length, days);
  assert.equal(overview.days, days);
  assert.equal(overview.totals.regulations, overview.markets.reduce((sum, row) => sum + row.count, 0));
  assert.equal(overview.totals.sources, overview.sources.length);
  assert.equal(overview.totals.scans, overview.series.reduce((sum, row) => sum + (row.scans || 0), 0));
  results.push({ days, totals: overview.totals, coverage: overview.coverage });
}
const authenticated = await request("/admin", { headers });
assert.equal(authenticated.status, 200);
const logout = await request("/api/admin/logout", { method: "POST", headers: { ...headers, Origin: base } });
assert.equal(logout.status, 200);
const replay = await request("/api/admin/overview", { headers });
assert.equal(replay.status, 401, "退出后旧凭据不能重放");
console.log(JSON.stringify({ verifiedAt: new Date().toISOString(), base, checks: ["匿名拒绝", "伪造会话拒绝", "页面跳转", "跨站登录拒绝", "错误密码拒绝", "安全Cookie", "日期校验", "7/30/90天聚合", "退出后会话撤销"], results }, null, 2));
